### ISSUE TITLE
Esx billing

### ISSUE THREAD

**Issue by Jamal209** [esx-framework/esx-legacy#117]
![sa](https://user-images.githubusercontent.com/99092590/154804348-a1f4ebca-8cbf-4963-ab6b-124e45911df8.png)
so here im trying to pay my invoice and got this error

**Comment by PsychoShock** [comment]
Fix with https://github.com/esx-framework/esx-legacy/pull/118

Thanks

**Comment by Jamal209** [comment]
> Fix with #118
> 
> Thanks

no problem thx
