### ISSUE TITLE
esx_addonaccount

### ISSUE THREAD

**Issue by Jamal209** [esx-framework/esx-legacy#121]
![saaa](https://user-images.githubusercontent.com/99092590/155258273-201e2d68-29e0-4515-94b5-27f2e11a2a0f.png)
i have problem with my startup about addon account.. ive been searching for something missing init

**Comment by balkanastrarp** [comment]
Looks like you didn't import the sql...

**Comment by Jamal209** [comment]
![sasa](https://user-images.githubusercontent.com/99092590/155717317-166b6b60-fe3c-40a0-bd65-40d1fa57eac2.png)


> Looks like you didn't import the sql...

i did import the sql and everything is in the line i think

**Comment by Jamal209** [comment]
![sasa](https://user-images.githubusercontent.com/99092590/155718125-c37ecf43-97c3-4d61-814e-ab99549583ff.png)
i just dont get it how left join and right join should be function..if iknew it probably get fix i think hehe

**Comment by balkanastrarp** [comment]
> ![sasa](https://user-images.githubusercontent.com/99092590/155718125-c37ecf43-97c3-4d61-814e-ab99549583ff.png) i just dont get it how left join and right join should be function..if iknew it probably get fix i think hehe

That script looks a bit weird to me... Have you installed it from the esx legacy?

**Comment by Jamal209** [comment]
> > ![sasa](https://user-images.githubusercontent.com/99092590/155718125-c37ecf43-97c3-4d61-814e-ab99549583ff.png) i just dont get it how left join and right join should be function..if iknew it probably get fix i think hehe
> 
> That script looks a bit weird to me... Have you installed it from the esx legacy?

yes i installed it from esx legacy but not from the latest one uses ox
