### ISSUE TITLE
es_extended commands not working

### ISSUE THREAD

**Issue by balkanastrarp** [esx-framework/esx-legacy#126]
So basically I was on the old version of es_extended (v1.2.0), and a couple of days ago, I decided to switch to the newest version of it, and right now, I imported scripts like that are recommended to have, and when I did, I joined the server, no errors, es_extended commands do not work ingame, they don't show up in the chat, but I can run them through the console. Also for me, the register menu does not show up... Still no errors...

**Comment by janwichmann12** [comment]
However, I can only agree some commands do work
For me the /car command does not work when I add another usergroup.
In the server.cfg is admin with all rights in it but if I write the added group "dev" in the es_extended and then ingame test comes no auto

**Comment by balkanastrarp** [comment]
> However, I can only agree some commands do work For me the /car command does not work when I add another usergroup. In the server.cfg is admin with all rights in it but if I write the added group "dev" in the es_extended and then ingame test comes no car

In the text chat, for me, commands do not show up, I have the highest group set, and it says "Access denied for command X".. If I run it from the console it works.. Don't know what it is caused by, I'm gonna switch to an older version of esx legacy and I am gonna update you right after downgrading. No support from esx legacy team about this issue....

**Comment by janwichmann12** [comment]
I have now managed it with the right and /car also works again :)

Am Fr., 25. Feb. 2022 um 22:05 Uhr schrieb balkanastrarp <
***@***.***>:

**Comment by PsychoShock** [comment]
This is not really a ESX issue since YOU are the one who merge to newest version. Please join the Discord to get help.
