### ISSUE TITLE
Esx garage bug

### ISSUE THREAD

**Issue by Kekk0x** [esx-framework/esx-legacy#128]
After leaving the car from the garage the map becomes like this
![Desktop Screenshot 2022 02 27 - 13 23 51 46](https://user-images.githubusercontent.com/100416558/155882238-7795b76e-c2b7-4209-9612-fa6e315bcd3a.png)

**Comment by PsychoShock** [comment]
Not a issue, this is from something else. Nothing is call in the garage function for radar. This can be closed @Mycroft-Studios
