### ISSUE TITLE
esx_multicharacter

### ISSUE THREAD

**Issue by LielXD** [esx-framework/esx-legacy#14]
how can I find the identifier of the current character?

**Comment by thelindat** [comment]
xPlayer.identifier returns the modified identifier.
xPlayer.license returns the normal value.

**Comment by LielXD** [comment]
> xPlayer.identifier returns the modified identifier.
> xPlayer.license returns the normal value.

im trying to make the ooc chat to be like this : ooc | full char name
how can i do that its gives me that error
![image](https://user-images.githubusercontent.com/60383662/127708462-51378ecc-63fd-475c-8381-41e7b1c4359a.png)

**Comment by LielXD** [comment]
solved!

**Comment by gunsela92** [comment]
How did you solve that ?

**Comment by LielXD** [comment]
@gunsela92 I just needed the name of the character so I just did:

xPlayer.getName()
