### ISSUE TITLE
First Spawn Change

### ISSUE THREAD

**Issue by Itzmezzzzz** [esx-framework/esx-legacy#161]
How to change first spawn after registering in esx_identity by default it spawns players in job centre how to change it! Using esx_multicharacter any solution please!

**Comment by LEGITIRONY** [comment]
This is not an actual is but i think you can find in your data base under the users table that you need to edit the default coords for the position column 
![positon defaults](https://user-images.githubusercontent.com/101866830/159101059-b1b7fae3-fb43-4fea-9a52-aa6f3ab24e86.png)

**Comment by Itzmezzzzz** [comment]
> I'm not sure this is an actual issue with esx but more your configuration. I think you can find in your data base under the users table that you need to edit the default coords for the position column this will change your default position. ![positon defaults](https://user-images.githubusercontent.com/101866830/159101059-b1b7fae3-fb43-4fea-9a52-aa6f3ab24e86.png)
> 
> How ever if you are after changing the character selection scene for multi characters that will be in its configuration for esx_multicharacter.

Thank you it worked

**Comment by LEGITIRONY** [comment]
Glad I could help :)

**Comment by Itzmezzzzz** [comment]
It was mentioned is es_extended SQL...
