### ISSUE TITLE
Issue with esx_vehicleshop

### ISSUE THREAD

**Issue by mr-capy** [esx-framework/esx-legacy#166]
Config.EnablePlayerManagement     = true
then when pop vehicle or put out vehicle for sale then this vehicle name always nill i tested it on ingame vehicles like blista and etc
i am also providing screenshot
![Screenshot (103)](https://user-images.githubusercontent.com/78591839/159157431-f664cbb4-dcb0-4cff-a611-339cb9635b61.png)

**Comment by LEGITIRONY** [comment]
Have you modified this esx_vehicleshop and have you imported the sql file correctly, also are you getting any errors in your F8 or console

**Comment by mr-capy** [comment]
Didn't modify and also correctly imported sql everything else is fine when purchasing vehicle but in this menu it shows nill

**Comment by Bluxrs** [comment]
Add the name and model into the database, see what it returns then. If it still does not show then probably a bug but I doubt it as it looks in order in the client and server.lua files for getting vehicle label

**Comment by mr-capy** [comment]
> Add the name and model into the database, see what it returns then. If it still does not show then probably a bug but I doubt it as it looks in order in the client and server.lua files for getting vehicle label

I was using the ingame vehicles which are in vehicles table also with model price etc but still same

**Comment by CsokiHUN** [comment]
I fixed this bug, check it out. [https://github.com/esx-framework/esx-legacy/pull/250](url)
