### ISSUE TITLE
missing config option for ox_inventory?

### ISSUE THREAD

**Issue by coresync2k** [esx-framework/esx-legacy#173]
i looked into the config.cfg from es_extended and some other configs but i dont find any option to enable or disable ox_inventory.
is this missing?

**Comment by LEGITIRONY** [comment]
i believe it dose a check automatically for ox inventory resource and if the resource is running it sets it to true in the server side or client cant remember but i thought i saw something in there for it 
`
if GetResourceState('ox_inventory') ~= 'missing' then
	Config.OxInventory = true
	SetConvarReplicated('inventory:framework', 'esx')
	SetConvarReplicated('inventory:weight', Config.MaxWeight * 1000)
end`
