### ISSUE TITLE
LAst update

### ISSUE THREAD

**Issue by frazz1234** [esx-framework/esx-legacy#178]
[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:308: attempt to index a nil value (local 'xPlayer')
[  script:es_extended] > handler (@es_extended/server/main.lua:308)
[  script:es_extended] > handler (@chat/sv_chat.lua:27)

**Comment by Bluxrs** [comment]
> [ script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:308: attempt to index a nil value (local 'xPlayer') [ script:es_extended] > handler (@es_extended/server/main.lua:308) [ script:es_extended] > handler (@chat/sv_chat.lua:27)

Add the code?
