### ISSUE TITLE
Access denied command for user

### ISSUE THREAD

**Issue by hichay1** [esx-framework/esx-legacy#18]
If player in user group. they cant use any user command such as info , job , group

**Comment by LielXD** [comment]
add those to server.cfg
```cfg
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow
```

**Comment by Luke20201** [comment]
Issued closed due to no responses from user.

If you are still experiencing this issue, you may reopen your issue, or make a new one.
