### ISSUE TITLE
Instance

### ISSUE THREAD

**Issue by frazz1234** [esx-framework/esx-legacy#181]
[     script:instance] SCRIPT ERROR: @instance/server/main.lua:26: attempt to call a nil value (global 'loadstring')

**Comment by Esplike** [comment]
Thank you, i'll look into it

**Comment by Mycroft-Studios** [comment]
your using an edited instance that has a backdoor in, nothing todo with us :)

**Comment by Mycroft-Studios** [comment]
> 

nope, that code doesn't exist for us, thats a third party copy :)
