### ISSUE TITLE
esx_taxijob markers bug

### ISSUE THREAD

**Issue by DonJoan** [esx-framework/esx-legacy#194]
![IMG_20220406_164322](https://user-images.githubusercontent.com/71422908/161988768-21dba44b-041f-4bb9-8af9-ba8f7fa41381.png)

![unknown-49](https://user-images.githubusercontent.com/71422908/161759326-d110f77f-660d-4cd7-b62a-8f6aae834622.png)
Job no have markers

**Comment by TheLazarusRising** [comment]
As a side note, please download VSCode or Notepad++ and stop using notepad
