### ISSUE TITLE
Es_extended not saving data to database

### ISSUE THREAD

**Issue by Steven-verhoef** [esx-framework/esx-legacy#196]
Es_extended not saving data to database
Only using es_extended and oxmysql all the newest version!
NO changes made to any of the scripts!
Also no saving message in TX admin
Forum link: https://forum.cfx.re/t/oxmysql-database-doesnt-save-data/4835366

**Comment by Mycroft-Studios** [comment]
The issue is your running incompatible scripts

**Comment by Steven-verhoef** [comment]
> The issue is your running incompatible scripts

The only scripts in the server are the ones from the newest esx legacy ?
