### ISSUE TITLE
Attempt to index a nil value (local 'xPlayer') on every script

### ISSUE THREAD

**Issue by gunsela92** [esx-framework/esx-legacy#20]
![Picture](https://user-images.githubusercontent.com/35037442/128946071-2cc9bfdb-4d44-405e-92cd-a05fb650f95a.png)

Im getting this error. Tried to install again and again. Cant fix it.  Im using default esx_skin btw

My cfg ;

![Picture2](https://user-images.githubusercontent.com/35037442/128946114-ee86eef3-e3c4-45e6-ba0d-9c495aaf763f.png)

**Comment by gunsela92** [comment]
Fixed. Error occurs because of esx_identity. Replaced with original one.

**Comment by x0Z3ro0x** [comment]
What original one is that? The one released is the original just with edits. So what version solved the issue for you? Going back too far results in the UI not loading properly.
