### ISSUE TITLE
es_extended: pickup props floating

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#204]
`esx:createMissingPickups` will create props floating in the air after player reconnects.

![image](https://user-images.githubusercontent.com/29688478/162634211-be6cd850-e2f4-4a72-a72e-b62094fca68b.png)

**Comment by mr-capy** [comment]
I think this fixed yesterday now you can close it i see this in changes on discord

**Comment by iSentrie** [comment]
> I think this fixed yesterday now you can close it i see this in changes on discord

have you tested it? here's results:
https://github.com/esx-framework/esx-legacy/commit/e829bf94a4a3770414b847ac5dd58a6bddf092ca

**Comment by mr-capy** [comment]
> > I think this fixed yesterday now you can close it i see this in changes on discord
> 
> have you tested it? here's results:
> https://github.com/esx-framework/esx-legacy/commit/e829bf94a4a3770414b847ac5dd58a6bddf092ca

He can confirm this coz I didn't get this issue

**Comment by iSentrie** [comment]
interesting...

**Comment by Benzo00** [comment]
done
