### ISSUE TITLE
esx_vehicleshop Locales[XX] does not exist?!

### ISSUE THREAD

**Issue by ncls-alien** [esx-framework/esx-legacy#208]
Hello,

I'm helping a friend with his server. Everything works fairly fine so far except this.

When entering the car dealer to buy a vehicle, everything is pretty much "Locales[XX] does not exist".

The issue is that there is no language file whatsoever to add text any text.

**Comment by iSentrie** [comment]
Everything is fine with that, you made modifications and failed to set language name, probably.

**Comment by ncls-alien** [comment]
Can't be. It was already like that when I freshly installed ESX and tested it without modifying anything.

**Comment by ncls-alien** [comment]
@Mycroft-Studios Then where is my mistake? The missing parts are not in the translation file of esx_vehicleshop.

I went through ever single folder on the server trying to find where the missing file is supposed to be and didn't find anything.

Also it was like that right after the installation with not a single modification made to any file.

At least give me a hint or something...
