### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by Crispyrox** [esx-framework/esx-legacy#21]
were it shows the bridge and it says loading scripts, it just keeps loading. help.

**Comment by Roydeking52** [comment]
Do you get F8 errors? Do you get console errors? With out any information nobody can help you!!!!!!

**Comment by x0Z3ro0x** [comment]
If you are using the multicharacters that come with this GitHub, that is a bug. It happens for me too, you just stay loading forever. Disabling it will fix that. If it's not from multicharacters, then I have no idea. Try giving more information about your issue so we can get help.

The reason the majority of tickets go unanswered around here is from the sheer lack of information being given to the developers.
