### ISSUE TITLE
First time needed restart for see register menu

### ISSUE THREAD

**Issue by TheDiego845** [esx-framework/esx-legacy#215]
I am using esx 1.6.5 and the first time I log in I see a black screen and it stays in awaiting script.
and after restarting I see the registration menu, I am using esx indentity not others like Roddy's Identity etc.

First time and second time in console
![image](https://user-images.githubusercontent.com/69425536/164314944-5e538fc7-99b7-4a07-ab37-6d6af793063b.png)

**Comment by Benzo00** [comment]
Database issue on ur end.
