### ISSUE TITLE
Bug LSPD

### ISSUE THREAD

**Issue by Firewolfs** [esx-framework/esx-legacy#22]
Hello, we have a bug with esx_police addon. Indeed, when we are in LSPD job and we disconnect from server, when we re-connect to server we haven't access to interaction points in the commisariat and to F6 menu. However, we still have access to the LSPD business management menu from the F5 menu.

**Comment by thelindat** [comment]
That was already patched if you look at commits

**Comment by Firewolfs** [comment]
Oh ok my bad, we used the release version in .zip, so we not seen that bug was fixed at commits.
Thank.
