### ISSUE TITLE
character doesnt get registered

### ISSUE THREAD

**Issue by maxcamorra** [esx-framework/esx-legacy#237]
I enter everything correct inside the identity form but nothing happens when i click on submit.
Firstname: Max
Lastname: Camorra
DOB: 06/19/1998
Height: 180

![image](https://user-images.githubusercontent.com/78707245/166113613-a70cc559-4b3a-44a7-b056-b667f4009a25.png)

**Comment by mr-capy** [comment]
Please read config for the max height possible to register character

**Comment by maxcamorra** [comment]
Config.MinHeight        = 120
Config.MaxHeight        = 220

its all correct 
180 is inside the range.

**Comment by mr-capy** [comment]
> Config.MinHeight        = 120
> Config.MaxHeight        = 220
> 
> its all correct 
> 180 is inside the range.

You download the latest version of identity? Try to restsrt coz for me sometime it didn't work on single try i don't know why

**Comment by maxcamorra** [comment]
yes latest version of the whole esx-legacy repo now. and still its not how it should work if i have to restart and see if it works or not...

**Comment by maxcamorra** [comment]
fixed with latest commit
