### ISSUE TITLE
Does ESX Legacy work with ESX 1.2 Scripts

### ISSUE THREAD

**Issue by yiruzu** [esx-framework/esx-legacy#253]
Can I just replace/install ESX Legacy and all scripts are working?

**Comment by Mycroft-Studios** [comment]
From our FAQ: 

**

> Question: Will [insert script name here] Work on legacy?

**

99% of Scripts made for v1-final and 95% of the scripts for 1.2 will work with ESX Legacy. However,if the the script is made for 1.1 or essentialmode, It will not work with ESX Legacy.
The Reasons a v1-final Script May Not Be compatible: Changes the Logic for Spawning Players
The Reasons a  1.2 Script May Not Be compatible: V1-Final Reasons, Uses the User_accounts database table.
