### ISSUE TITLE
esx_garage issue

### ISSUE THREAD

**Issue by laazaaroo** [esx-framework/esx-legacy#254]
When you store a vehicle in a garage, when you go out and come back in to take it out, it is not there, it has moved to another garage and you have to look for it in the different garages on the map. Also there are no garages in the north.

**Comment by laazaaroo** [comment]
Or sometimes gets duplicated
video: https://streamable.com/ppovhr

**Comment by xorzo1** [comment]
Is this on latest?

**Comment by laazaaroo** [comment]
In 1.6.0 and 1.7.0

**Comment by Benzo00** [comment]
New garage system is being worked on
