### ISSUE TITLE
[      script:oxmysql] [WARNING] esx_status took 896.620105ms to execute a query! 

### ISSUE THREAD

**Issue by Tinky124** [esx-framework/esx-legacy#258]
[      script:oxmysql] [WARNING] esx_status took 896.620105ms to execute a query!
[      script:oxmysql]     UPDATE users SET status = ? WHERE identifier = ? ["[{\"val\":986200,\"percent\":98.61999999999999,\"name\":\"hunger\"},{\"val\":989650,\"percent\":98.965,\"name\":\"thirst\"}]","char1:02eca0c76647721f2da4bce89ee96716309fedbf"]

**Comment by Benzo00** [comment]
not an issue with esx.
