### ISSUE TITLE
maybe inverted

### ISSUE THREAD

**Issue by DonJoan** [esx-framework/esx-legacy#260]
esx_vehicleshop cars inverted 
https://streamable.com/iadtuu

**Comment by PandaSLO** [comment]
No, as far as i know this is how it's supposed to be.

**Comment by Mycroft-Studios** [comment]
can u explain the issue :)

**Comment by DonJoan** [comment]
See comet 2 name is comet 5 and comet 5 name comet
And see comet price is 65 000 when I click to buy price is 1 145 000
![Screenshot_20220516_012845_com android chrome](https://user-images.githubusercontent.com/71422908/168496608-3fe5645e-6863-47b4-a1e9-dbbcf1d1ee4b.jpg)
![Screenshot_20220516_012836_com android chrome](https://user-images.githubusercontent.com/71422908/168496610-698bc058-28ea-43b8-845c-010bf43a99ad.jpg)
