### ISSUE TITLE
Backpack iventory

### ISSUE THREAD

**Issue by Davinel17** [esx-framework/esx-legacy#27]
with the legacy version ,  it have a way to add backpack weight ,  i know is enable into the esx2  but it is possible into the legacy one ?

thank you very much

**Comment by Roydeking52** [comment]
i have it in my esx clotheshop it support backpack weight

**Comment by Luke20201** [comment]
Hi,

This is not available in the ESX-Repo. You can however search the FiveM forums for a public release of this.
