### ISSUE TITLE
skinchanger 1.7.5

### ISSUE THREAD

**Issue by laazaaroo** [esx-framework/esx-legacy#271]
Translations arent well, now are with mum, dad and those things and es are optdated
![image](https://user-images.githubusercontent.com/70603123/169865878-885d66b5-1d90-407b-a874-223a09be4c89.png)
![image](https://user-images.githubusercontent.com/70603123/169865919-a6ddfb66-1342-44b8-835d-fb8d4a1daff6.png)

![image](https://user-images.githubusercontent.com/70603123/169865700-3fcd402c-59fe-4ea7-a782-acbab13e90c6.png)

**Comment by Benzo00** [comment]
if u understand "es" go ahead and make a pr

**Comment by laazaaroo** [comment]
Ok, Will do It👌

**Comment by laazaaroo** [comment]
Its done, you have to accept It

**Comment by laazaaroo** [comment]
Locales['es'] = {
  ['sex'] = 'sexo',
  ['mom'] = 'cara de la madre',
  ['dad'] = 'cara del padre',
  ['resemblance'] = 'parecido',
  ['skin_tone'] = 'tono de piel',
  ['nose_1'] = 'ancho de la nariz',
  ['nose_2'] = 'altura del pico de la nariz',
  ['nose_3'] = 'longitud del pico de la nariz',
  ['nose_4'] = 'altura del hueso de la nariz',
  ['nose_5'] = 'bajada del pico de la nariz',
  ['nose_6'] = 'torsión del hueso de la nariz',
  ['cheeks_1'] = 'altura de los pómulos',
  ['cheeks_2'] = 'anchura de los pómulos',
  ['cheeks_3'] = 'ancho de las mejillas',
  ['lip_fullness'] = 'relleno de los labios',
  ['jaw_bone_width'] = 'anchura del hueso de la mandíbula',
  ['jaw_bone_length'] = 'longitud del hueso de la mandíbula',
  ['chin_height'] = 'altura de la barbilla',
  ['chin_length'] = 'longitud de la barbilla',
  ['chin_width'] = 'ancho de la barbilla',
  ['chin_hole'] = 'tamaño del agujero de la barbilla',
  ['neck_thickness'] = 'grosor del cuello',
  ['wrinkles'] = 'arrugas',
  ['wrinkle_thickness'] = 'cantidad de arrugas',
  ['beard_type'] = 'tipo de barba',
  ['beard_size'] = 'tamaño de la barba',
  ['beard_color_1'] = 'color de la barba 1',
  ['beard_color_2'] = 'color de la barba 2',
  ['hair_1'] = 'pelo 1',
  ['hair_2'] = 'pelo 2',
  ['hair_color_1'] = 'color de pelo 1',
  ['hair_color_2'] = 'color de pelo 2',
  ['eye_color'] = 'color de ojos',
  ['eye_squint'] = 'achinado de ojos',
  ['eyebrow_type'] = 'tipo de ceja',
  ['eyebrow_size'] = 'tipo de ceja',
  ['eyebrow_color_1'] = 'color de ceja 1',
  ['eyebrow_color_2'] = 'color de ceja 2',
  ['eyebrow_depth'] = 'profundidad de las cejas',
  ['eyebrow_height'] = 'altura de las cejas',
  ['makeup_type'] = 'tipo de maquillaje',
  ['makeup_thickness'] = 'cantidad de maquillaje',
  ['makeup_color_1'] = 'color de maquillaje 1',
  ['makeup_color_2'] = 'color de maquillaje 2',
  ['lipstick_type'] = 'tipo de pintalabios',
  ['lipstick_thickness'] = 'cantidad de pintalabios',
  ['lipstick_color_1'] = 'color de pintalabios 1',
  ['lipstick_color_2'] = 'color de pintalabios 2',
  ['ear_accessories'] = 'accesorios de oreja',
  ['ear_accessories_color'] = 'color de accesorios',
  ['tshirt_1'] = 'camiseta 1',
  ['tshirt_2'] = 'camiseta 2',
  ['torso_1'] = 'torso 1',
  ['torso_2'] = 'torso 2',
  ['decals_1'] = 'tatuajes 1',
  ['decals_2'] = 'tatuajes 2',
  ['arms'] = 'brazos',
  ['arms_2'] = 'brazos 2',
  ['pants_1'] = 'pantalones 1',
  ['pants_2'] = 'pantalones 2',
  ['shoes_1'] = 'calzado 1',
  ['shoes_2'] = 'calzado 2',
  ['mask_1'] = 'mascara 1',
  ['mask_2'] = 'mascara 2',
  ['bproof_1'] = 'chaleco antibalas 1',
  ['bproof_2'] = 'chaleco antibalas 2',
  ['chain_1'] = 'cadena 1',
  ['chain_2'] = 'cadena 2',
  ['helmet_1'] = 'casco 1',
  ['helmet_2'] = 'casco 2',
  ['watches_1'] = 'reloj 1',
  ['watches_2'] = 'reloj 2',
  ['bracelets_1'] = 'pulseras 1',
  ['bracelets_2'] = 'pulseras 2',
  ['glasses_1'] = 'gafas 1',
  ['glasses_2'] = 'gafas 2',
  ['bag'] = 'mochila',
  ['bag_color'] = 'color mochila',
  ['blemishes'] = 'manchas',
  ['blemishes_size'] = 'cantidad de manchas',
  ['ageing'] = 'envejecimiento',
  ['ageing_1'] = 'cantidad de envejecimiento',
  ['blush'] = 'colorete',
  ['blush_1'] = 'cantidad de colorete',
  ['blush_color'] = 'color de colorete',
  ['complexion'] = 'complexión',
  ['complexion_1'] = 'cantidad de complexión',
  ['sun'] = 'bronceado',
  ['sun_1'] = 'cantidad de bronceado',
  ['freckles'] = 'pecas',
  ['freckles_1'] = 'cantidad de pecas',
  ['chest_hair'] = 'vello corporal',
  ['chest_hair_1'] = 'cantidad de vello corporal',
  ['chest_color'] = 'color de vello corporal',
  ['bodyb'] = 'manchas en el cuerpo',
  ['bodyb_size'] = 'tipo de manchas en el cuerpo',
  ['bodyb_extra'] = 'efecto de manchas en el cuerpo',
  ['bodyb_extra_thickness'] = 'espesor de manchas efecto cuerpo',
}

**Comment by Benzo00** [comment]
Make a pr if u know how to do it :)

**Comment by laazaaroo** [comment]
I dont know srry

**Comment by Benzo00** [comment]
Fixed
