### ISSUE TITLE
esx_jobs not working correctly

### ISSUE THREAD

**Issue by xGeekoo** [esx-framework/esx-legacy#284]
I can't interact with circle to collect wool with tailor job.
It seems to work only 1 out of 20 times when stay in the circle considering the number of seconds specified in the config file.

I use latest esx-legacy-main.
I don't have any error in the console.
Same issue with or without onesync.

**Comment by Benzo00** [comment]
Being worked on. new esx job will soon come out

**Comment by JohnnyS** [comment]
Still being worked on?

**Comment by xGeekoo** [comment]
According to the information I have this is an old code that needs to be completely reworked.
Could be take 1 month or 1 years.

**Comment by JohnnyS** [comment]
Oh okay well soon isnt a year 😂 but then I'll just hold off on this

**Comment by Benzo00** [comment]
will come in 1.8 update
