### ISSUE TITLE
bug (es_extended): vehicle properties

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#285]
This brings new issues with boats, probably because it doesn't have wheels. Error's can be replicated by spawning a saved vehicle from any garage script which utilizes ESX vehicle properties.

https://github.com/esx-framework/esx-legacy/blob/5fa75840e65d625160204f373014f09d3b10bc51/%5Besx%5D/es_extended/client/functions.lua#L617-L632

**Comment by Slewog** [comment]
You can try to set a condition if the vehicle class is  bot or plane just past this code and set the values all values to false

**Comment by Slewog** [comment]
You have this error just about boat or with planes too ? With bikes and car do you have an issues?

**Comment by Slewog** [comment]
Maybe fix on my PR, it's working with the fix on my server

**Comment by Kenta30** [comment]
Now it's working

**Comment by Slewog** [comment]
> Now it's working

Nice, with my pr or not?

**Comment by Kenta30** [comment]
Sure, with yours

**Comment by Slewog** [comment]
> 

No, the bug is still present, I just tested it, pr #293 does not solve the esx_garage problem.

**Comment by iSentrie** [comment]
Fixed in:
[Formatting + Boat Fixes](https://github.com/esx-framework/esx-legacy/commit/7a53a19c1bc20ce72a9a9c9f39aa54a6931adb34)
