### ISSUE TITLE
bug (esx_lscustom): free tuning glitch

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#289]
Free tuning

1. Select desired change on vehicle
2. Disconnect
3. Free tuning

https://streamable.com/dfgsy3

**Comment by xorzo1** [comment]
Are you on latest legacy? 

https://github.com/esx-framework/esx-legacy/commit/167385206b90f77648d24888af81e5343cdab85d

**Comment by iSentrie** [comment]
Yes, that was the whole idea to replicate these old bugs on new version.

**Comment by xorzo1** [comment]
In the latest lscustom it cancels when you disconnect. I just tried?

**Comment by iSentrie** [comment]
Not for me, source version.
https://streamable.com/ahavv5

**Comment by Mycroft-Studios** [comment]
I will look into, its supposed to cancel the update on leave though

**Comment by mr-capy** [comment]
I think its fixed?

**Comment by iSentrie** [comment]
no it's not.

**Comment by AstroNext** [comment]
fixed in #609 PR.

Thanks to @iSentrie for help in testing resource

**Comment by iSentrie** [comment]
#609
