### ISSUE TITLE
Attemt to nil value

### ISSUE THREAD

**Issue by JannikHoerth** [esx-framework/esx-legacy#29]
Hello,

i installed the script and set up all Shops to false exepted the Truck-Shop.

When I try to start the script I get following error:
[script:esx_advancedv] SCRIPT ERROR: @esx_advancedvehicleshop/server/main.lua:52: attempt to call a nil value (global 'mysqlTruck')

When i´m activating the Boat-Shop and deactivate the Truckshop I´ll get the same error, just with the mysqlBoat

Can someone help me?

**Comment by Luke20201** [comment]
Hi, this resource is not apart of the ESX repo. 
Please create an issue on the repo of the esx_advancedvehicleshop github.
