### ISSUE TITLE
bug? (esx_multicharacter + esx_skin?) - Female Ped will show male model 

### ISSUE THREAD

**Issue by JohnnyS** [esx-framework/esx-legacy#296]
I been having reports of one person female character will show a male model with glitched out clothing but have the same numbers that the female model had. The weird thing is in the database the sex is 1 and not 0 but in game it is showing my player a male model. If I have them use a skin menu and change the sex to 0 then 1 again the model loads up fine but this is annoying as they would have to either relog or change the skin multiple times until their model loads up properly.

I have tried to change the database value of sex to 0 and had them use the menu to save to the database so the skin is 1 but that did not help. I had them clear their cache and no go. This seems to only be effecting female models, I have a small number of females in my community the other one doesnt have a 2nd character so cant confirm with her yet but I have a female character but have not had that issue happen to me. I am not sure what could be causing it could it be multi char or skin or skinchanger?? Im not too sure

Heres an ex of what the database shows

{"torso_2":2,"bodyb_2":0,"eye_squint":0,"nose_4":10,"chest_3":0,"arms":15,"bracelets_2":0,"decals_2":0,"lipstick_4":0,"bodyb_4":0,"bags_1":0,"beard_2":0,"bodyb_3":-1,"makeup_2":10,"pants_1":15,"blush_1":0,"blemishes_1":0,"watches_1":-1,"bproof_1":0,"hair_1":21,"eyebrows_1":5,"nose_1":-10,"jaw_1":0,"bracelets_1":-1,"tshirt_1":14,"chin_4":0,"hair_2":0,"shoes_1":6,"hair_color_2":17,"makeup_3":21,"jaw_2":0,"age_1":0,"lipstick_3":50,"complexion_1":0,"eyebrows_6":0,"mask_1":0,"pants_2":1,"sun_2":0,"sex":1,"nose_5":0,"chin_2":0,"blemishes_2":0,"nose_6":0,"chin_1":0,"neck_thickness":0,"moles_2":10,"ears_1":-1,"dad":0,"torso_1":25,"complexion_2":0,"skin_md_weight":58,"helmet_1":-1,"blush_2":0,"makeup_4":0,"cheeks_3":0,"bodyb_1":-1,"cheeks_2":0,"nose_3":10,"lipstick_2":7,"makeup_1":5,"nose_2":-8,"chain_1":0,"cheeks_1":0,"moles_1":12,"glasses_1":5,"chin_3":0,"face_md_weight":20,"chest_2":0,"blush_3":0,"mask_2":0,"beard_3":0,"lipstick_1":4,"helmet_2":0,"hair_color_1":22,"bproof_2":0,"shoes_2":2,"eyebrows_4":0,"lip_thickness":4,"mom":21,"age_2":0,"chain_2":0,"beard_4":0,"watches_2":0,"chest_1":0,"tshirt_2":0,"glasses_2":0,"chin_13":0,"eye_color":2,"eyebrows_5":0,"eyebrows_2":10,"decals_1":0,"ears_2":0,"eyebrows_3":0,"arms_2":0,"beard_1":0,"bags_2":0,"sun_1":0}

**Comment by Antho7Twitch** [comment]
Hi @JohnnyS,

You can try to delete her character in the DB and tell her to create it again, just in case it was only a puntual error.

Give it a try, if it's not working you can try to create yourself a character and test it out with prints.

Good luck and tell us about after testing!

Cheers! ❤️

**Comment by Mycroft-Studios** [comment]
update your esx :)

**Comment by JohnnyS** [comment]
What exactly am I updating lol? I already pushed out my server to production like a week or two after 1.7.5 was released but I didn't have the time to go through all those changes, however I did do some manual changes. 

@Antho7Twitch  I have already had her delete the character through multichar and remake one but it still happened. 

@Mycroft-Studios  I will see all the changes but there are to much for me to push out to a live server could you let me know what exactly I need to update for this issue?

**Comment by Antho7Twitch** [comment]
Hi again @JohnnyS!

Have you checked the client and server console right in the moment she create the character? 
Cause maybe there's an error or something we can dig it out to know where's the problem.

It only happens to this girl or if you test it in your proper computer and you create a woman it happens to you too?

In case you need more help and Mycroft didn't have the time to help (cause probably he has so much work) i can try it via DM if you need it.

Have a nice day!

**Comment by JohnnyS** [comment]
![image](https://user-images.githubusercontent.com/62607662/172194005-3188aed5-d573-4756-bcea-7eb8c588f87e.png)

```lua
if not v.model and v.skin then
					if v.skin.model then v.model = v.skin.model elseif v.skin.sex == 0 then v.model = GetHashKey("mp_m_freemode_01") else v.model = GetHashKey("mp_f_freemode_01") end
print("I am a ")
print(v.skin.sex)
print(v.skin.model)
print(v.model)
end
```

I do believe this is the issue and potential fix lol

My friend joined and this is what printed

[     90312] [b2545_GTAProce]             MainThrd/ I am a 
[     90312] [b2545_GTAProce]             MainThrd/ 0
[     90312] [b2545_GTAProce]             MainThrd/ nil
[     90312] [b2545_GTAProce]             MainThrd/ 1885233650

**Comment by Mycroft-Studios** [comment]
ahh, i forgot multicharacter had it seperate, will fix now

**Comment by Mycroft-Studios** [comment]
> > 
> 
> No errors appear when creating characters
> 
> > #263 - was fixed here
> 
> I have manually put those changes in my server before I went live however I do believe I may of found another issue that could be causing it. In the esx_multicharacter:SetupUI netevent there is
> 
> ```lua
> if not v.model and v.skin then
>          if v.skin.model then v.model = v.skin.model elseif v.skin.sex == 1 then v.model = GetHashKey("mp_m_freemode_01") else v.model = GetHashKey("mp_m_freemode_01") end
> end
> ```
> 
> Its showing mp_m twice I'm currently testing with this and putting some prints out, I am printing out the hashkey of a male as my female character and if I "switch" characters even without another slot my sex changed to male but in the /skin command it still shows 1.
> 
> I hope this makes sense can this be reopened?

yes, that is exactly what the pr fixed

**Comment by Mycroft-Studios** [comment]
https://github.com/esx-framework/esx-legacy/commit/99ee3c3e3a4ff7d05f072ee973cb9bed5ad0a45e - fixed

**Comment by JohnnyS** [comment]
Thank you good sir, however you have to set v.skin.sex == 0 so males are males and not females lol

**Comment by Antho7Twitch** [comment]
Perfect, have a nice day both of you ❤️
