### ISSUE TITLE
How to Remove Player name & ID above head?

### ISSUE THREAD

**Issue by Laalalaaalaa** [esx-framework/esx-legacy#30]
I have looked through almost every file, and even downloaded a script to try and remove playernames and ids above there head, with no success. I was hoping someone could help me or guide me through these files to try remove that. Picture of my players for example. Any help would be great! Thank you
![Desktop_Screenshot_2021 09 20_-_19 44 50 14](https://user-images.githubusercontent.com/90179242/134133641-4b03bf18-9dd5-49cc-b5fa-829983f3e7df.png)

**Comment by iSentrie** [comment]
not related to esx

**Comment by Roydeking52** [comment]
esx doesnt have a default head id scirpt you have added it yourself

**Comment by Luke20201** [comment]
Hi, this issue is not related to ESX. From memory, I believe this is from vMenu.
