### ISSUE TITLE
Users have es_extended admin commands

### ISSUE THREAD

**Issue by SilverLeBebeOurs** [esx-framework/esx-legacy#326]
Users have es_extended admin commands

**Comment by SilverLeBebeOurs** [comment]
But suddenly where does it come from because I tried an esx legacy base template and there is the same bug

**Comment by Mycroft-Studios** [comment]
this isnt a esx issue, permissions are handled by ace perms, which is built into FiveM

**Comment by Mycroft-Studios** [comment]
Note on this: By default, CFX grant will admin permissions to the licence key holder of the server, regardless of esx group
