### ISSUE TITLE
Could you please add my simplified Chinese translation？

### ISSUE THREAD

**Issue by Tompizza** [esx-framework/esx-legacy#327]
Could you please add my simplified Chinese translation？ 

cn.lua

Locales['cn'] = {
    -- 库存
    ['inventory'] = '库存 ( 重量 %s / %s )',
    ['use'] = '使用',
    ['give'] = '给予',
    ['remove'] = '丢弃',
    ['return'] = '返回',
    ['give_to'] = '赠给',
    ['amount'] = '数量',
    ['giveammo'] = '给予弹药',
    ['amountammo'] = '弹药量',
    ['noammo'] = '你没有足够的弹药!',
    ['gave_item'] = '你把 %sx %s 赠给了 %s',
    ['received_item'] = '你收到 %sx %s 来自 %s',
    ['gave_weapon'] = '你把 %s 给了 %s',
    ['gave_weapon_ammo'] = '你把 ~o~%sx %s %s给了%s',
    ['gave_weapon_withammo'] = '你把 %s 和 ~o~%sx %s 给了 %s',
    ['gave_weapon_hasalready'] = '%s 已经拥有 %s',
    ['gave_weapon_noweapon'] = '%s 没有那个武器',
    ['received_weapon'] = '你收到了 %s 来自 %s',
    ['received_weapon_ammo'] = '你收到了 ~o~%sx %s  %s 来自 %s',
    ['received_weapon_withammo'] = '你收到了 %s 和 ~o~%sx %s 来自 %s',
    ['received_weapon_hasalready'] = '%s 试图给你 %s, 但你已经拥有了',
    ['received_weapon_noweapon'] = '%s 试图给你 %s, 弹药，但你没有那个武器',
    ['gave_account_money'] = '你将 $%s (%s) 给予 %s',
    ['received_account_money'] = '你收到了 $%s (%s) 来自 %s',
    ['amount_invalid'] = '无效数量',
    ['players_nearby'] = '附近没有玩家',
    ['ex_inv_lim'] = '无法执行操作，超过了最大重量 %s',
    ['imp_invalid_quantity'] = '无法执行操作，数量无效',
    ['imp_invalid_amount'] = '无法执行操作，金额无效',
    ['threw_standard'] = '你丢弃了 %sx %s',
    ['threw_account'] = '你丢弃了 $%s %s',
    ['threw_weapon'] = '你丢弃了 %s',
    ['threw_weapon_ammo'] = '你丢弃了 %s 和 ~o~%sx %s',
    ['threw_weapon_already'] = '你已经有同样的武器了',
    ['threw_cannot_pickup'] = '你不能再拿起那个了，因为你的库存已经满了',
    ['threw_pickup_prompt'] = '按 E 拿起',
  
    -- 按键显示
  ['keymap_showinventory'] = '显示库存',
  
    -- 薪资相关
    ['received_salary'] = '你收到了工资: $%s',
    ['received_help'] = '你领取到了你的失业救济金: $%s',
    ['company_nomoney'] = '你受雇的公司太穷了，无法支付你的工资',
    ['received_paycheck'] = '收到转账',
    ['bank'] = '花园银行',
    ['account_bank'] = '银行',
    ['account_black_money'] = '黑钱',
    ['account_money'] = '现金',
  
    ['act_imp'] = '操作失败',
    ['in_vehicle'] = '请离开载具',
  
    -- 命令
    ['command_bring'] = '把玩家带到你身边',
    ['command_car'] = '生成载具',
    ['command_car_car'] = '生成载具的模型名称或哈希值',
    ['command_cardel'] = '删除附近的载具',
    ['command_cardel_radius'] = '可选，删除指定半径内的所有车辆',
    ['command_clear'] = '清除聊天记录',
    ['command_clearall'] = '清除所有玩家的聊天记录',
    ['command_clearinventory'] = '清除玩家库存',
    ['command_clearloadout'] = '清除玩家皮肤',
    ['command_freeze'] = '冻结玩家',
    ['command_unfreeze'] = '解冻玩家',
    ['command_giveaccountmoney'] = '给指定账户的钱',
    ['command_giveaccountmoney_account'] = '要添加到的帐户',
    ['command_giveaccountmoney_amount'] = '添加金额',
    ['command_giveaccountmoney_invalid'] = '帐户名无效',
    ['command_giveitem'] = '给玩家一个物品',
    ['command_giveitem_item'] = '物品名字',
    ['command_giveitem_count'] = '数量',
    ['command_giveweapon'] = '给玩家一把武器',
    ['command_giveweapon_weapon'] = '武器名称',
    ['command_giveweapon_ammo'] = '弹药数量',
    ['command_giveweapon_hasalready'] = '该玩家已经拥有该武器',
    ['command_giveweaponcomponent'] = '给武器配件',
    ['command_giveweaponcomponent_component'] = '配件名称',
    ['command_giveweaponcomponent_invalid'] = '无效的武器配件',
    ['command_giveweaponcomponent_hasalready'] = '玩家已经拥有该武器配件',
    ['command_giveweaponcomponent_missingweapon'] = '该玩家没有那个武器',
    ['command_goto'] = '将自己传送给玩家',
    ['command_kill'] = '杀死一名玩家',
    ['command_save'] = '强制保存玩家数据',
    ['command_saveall'] = '强制保存所有玩家数据',
    ['command_setaccountmoney'] = '将钱存入指定账户',
    ['command_setaccountmoney_amount'] = '数量',
    ['command_setcoords'] = '传送到指定坐标',
    ['command_setcoords_x'] = 'X 轴',
    ['command_setcoords_y'] = 'Y 轴',
    ['command_setcoords_z'] = 'Z 轴',
    ['command_setjob'] = '设置玩家的工作',
    ['command_setjob_job'] = '工作名称',
    ['command_setjob_grade'] = '工作等级',
    ['command_setjob_invalid'] = '工作、等级或两者均无效',
    ['command_setgroup'] = '设置玩家用户组',
    ['command_setgroup_group'] = '用户组名称',
    ['commanderror_argumentmismatch'] = '参数计数不匹配(该类型为%s, 需要传递 %s)',
    ['commanderror_argumentmismatch_number'] = '参数 #%s 类型不匹配（该类型为字符串，需要传递数字类类型为字符串，需要传递数字类型）',
    ['commanderror_invaliditem'] = '无效的物品名称',
    ['commanderror_invalidweapon'] = '无效武器',
    ['commanderror_console'] = '该命令不能从控制台运行',
    ['commanderror_invalidcommand'] = '^3%s^0 不是有效的命令！',
    ['commanderror_invalidplayerid'] = '没有在线玩家匹配到该服务id',
    ['commandgeneric_playerid'] = '玩家id',
  
    -- 区域设置
    ['locale_digit_grouping_symbol'] = ',',
    ['locale_currency'] = '£%s',
  
    -- 武器
  
    -- 冷兵器
    ['weapon_dagger'] = '匕首',
    ['weapon_bat'] = '棒球棍',
    ['weapon_battleaxe'] = '战斧',
    ['weapon_bottle'] = '酒瓶',
    ['weapon_crowbar'] = '撬棍',
    ['weapon_flashlight'] = '手电筒',
    ['weapon_golfclub'] = '高尔夫球杆',
    ['weapon_hammer'] = '铁锤',
    ['weapon_hatchet'] = '手斧',
    ['weapon_knife'] = '小刀',
    ['weapon_knuckle'] = '手指虎',
    ['weapon_machete'] = '开山刀',
    ['weapon_nightstick'] = '警棍',
    ['weapon_wrench'] = '管钳扳手',
    ['weapon_poolcue'] = '台球杆',
    ['weapon_stone_hatchet'] = '石斧',
    ['weapon_switchblade'] = '弹簧刀',
  
    -- 手枪
    ['weapon_appistol'] = '穿甲手枪',
    ['weapon_ceramicpistol'] = '陶瓷手枪',
    ['weapon_combatpistol'] = '战斗手枪',
    ['weapon_doubleaction'] = '双动式左轮手枪',
    ['weapon_navyrevolver'] = '海军左轮手枪',
    ['weapon_flaregun'] = '信号枪',
    ['weapon_gadgetpistol'] = '毛瑟手枪',
    ['weapon_heavypistol'] = '重型手枪',
    ['weapon_revolver'] = '重型左轮手枪',
    ['weapon_revolver_mk2'] = '重型左轮手枪 MK2',
    ['weapon_marksmanpistol'] = '射手手枪',
    ['weapon_pistol'] = '手枪',
    ['weapon_pistol_mk2'] = '手枪 MK2',
    ['weapon_pistol50'] = '0.5 口径手枪',
    ['weapon_snspistol'] = '劣质手枪',
    ['weapon_snspistol_mk2'] = '劣质手枪 MK2',
    ['weapon_stungun'] = '电击枪',
    ['weapon_raypistol'] = '脉冲手枪',
    ['weapon_vintagepistol'] = '老式手枪',
  
    -- 霰弹枪
    ['weapon_assaultshotgun'] = '突击霰弹枪',
    ['weapon_autoshotgun'] = '半自动霰弹枪',
    ['weapon_bullpupshotgun'] = '无托式霰弹枪',
    ['weapon_combatshotgun'] = '战斗霰弹枪',
    ['weapon_dbshotgun'] = '双管霰弹枪',
    ['weapon_heavyshotgun'] = '重型霰弹枪',
    ['weapon_musket'] = '老式火枪',
    ['weapon_pumpshotgun'] = '泵动式霰弹枪',
    ['weapon_pumpshotgun_mk2'] = '泵动式霰弹枪 MK2',
    ['weapon_sawnoffshotgun'] = '短管霰弹枪',
  
    -- 冲锋枪 & 机器
    ['weapon_assaultsmg'] = '突击冲锋枪',
    ['weapon_combatmg'] = '战斗机枪',
    ['weapon_combatmg_mk2'] = '战斗机枪 MK2',
    ['weapon_combatpdw'] = '作战自卫冲锋枪',
    ['weapon_gusenberg'] = '古森柏冲锋枪',
    ['weapon_machinepistol'] = '冲锋手枪',
    ['weapon_mg'] = '机枪',
    ['weapon_microsmg'] = '微型冲锋枪',
    ['weapon_minismg'] = '迷你冲锋枪',
    ['weapon_smg'] = '冲锋枪',
    ['weapon_smg_mk2'] = '冲锋枪 MK2',
    ['weapon_raycarbine'] = '镭射激光枪',
  
    -- 突击步枪
    ['weapon_advancedrifle'] = '高级步枪',
    ['weapon_assaultrifle'] = '突击步枪',
    ['weapon_assaultrifle_mk2'] = '突击步枪 MK2',
    ['weapon_bullpuprifle'] = '无托式步枪',
    ['weapon_bullpuprifle_mk2'] = '无托式步枪 MK2',
    ['weapon_carbinerifle'] = '卡宾步枪',
    ['weapon_carbinerifle_mk2'] = '卡宾步枪 MK2',
    ['weapon_compactrifle'] = '紧凑型步枪',
    ['weapon_militaryrifle'] = '军用步枪',
    ['weapon_specialcarbine'] = '特制卡宾枪',
    ['weapon_specialcarbine_mk2'] = '特制卡宾枪 MK2',
  
    -- 狙击枪
    ['weapon_heavysniper'] = '重型狙击步枪',
    ['weapon_heavysniper_mk2'] = '重型狙击步枪 MK2',
    ['weapon_marksmanrifle'] = '射手步枪',
    ['weapon_marksmanrifle_mk2'] = '射手步枪 MK2',
    ['weapon_sniperrifle'] = '狙击步枪',
  
    -- 重型武器 / 发射器
    ['weapon_compactlauncher'] = '紧凑型榴弹发射器',
    ['weapon_firework'] = '烟花发射器',
    ['weapon_grenadelauncher'] = '榴弹发射器',
    ['weapon_hominglauncher'] = '制导火箭发射器',
    ['weapon_minigun'] = '火神机枪',
    ['weapon_railgun'] = '电磁轨道炮',
    ['weapon_rpg'] = '火箭炮',
    ['weapon_rayminigun'] = '重型镭射激光枪',
  
    -- 投掷物
    ['weapon_ball'] = '棒球',
    ['weapon_bzgas'] = '催泪瓦斯',
    ['weapon_flaregun'] = '信号枪',
    ['weapon_grenade'] = '手榴弹',
    ['weapon_petrolcan'] = '汽油桶',
    ['weapon_hazardcan'] = '危险汽油桶',
    ['weapon_molotov'] = '汽油弹',
    ['weapon_proxmine'] = '感应地雷',
    ['weapon_pipebomb'] = '土制炸弹',
    ['weapon_snowball'] = '雪球',
    ['weapon_stickybomb'] = '黏弹',
    ['weapon_smokegrenade'] = '烟雾弹',
  
    -- 特殊物品
    ['weapon_fireextinguisher'] = '灭火器',
    ['weapon_digiscanner'] = '数字扫描仪',
    ['weapon_garbagebag'] = '垃圾袋',
    ['weapon_handcuffs'] = '手铐',
    ['gadget_nightvision'] = '夜视镜',
    ['gadget_parachute'] = '降落伞',
  
    -- 武器配件
    ['component_knuckle_base'] = '基础涂装',
    ['component_knuckle_pimp'] = '皮条客涂装',
    ['component_knuckle_ballas'] = '巴拉斯涂装',
    ['component_knuckle_dollar'] = '骗子涂装',
    ['component_knuckle_diamond'] = '岩石涂装',
    ['component_knuckle_hate'] = '仇恨者涂装',
    ['component_knuckle_love'] = '情人涂装',
    ['component_knuckle_player'] = '玩家涂装',
    ['component_knuckle_king'] = '国王涂装',
    ['component_knuckle_vagos'] = '瓦戈斯涂装',
  
    ['component_luxary_finish'] = '高级武器涂装',
  
    ['component_handle_default'] = '默认涂装握把',
    ['component_handle_vip'] = 'VIP涂装握把',
    ['component_handle_bodyguard'] = '保镖保镖涂装握把',
  
    ['component_vip_finish'] = 'VIP涂装',
    ['component_bodyguard_finish'] = '保镖涂装',
  
    ['component_camo_finish'] = '数码迷彩',
    ['component_camo_finish2'] = '笔触迷彩',
    ['component_camo_finish3'] = '林地迷彩',
    ['component_camo_finish4'] = '骷髅迷彩',
    ['component_camo_finish5'] = '六十九迷彩',
    ['component_camo_finish6'] = '泰迪迷彩',
    ['component_camo_finish7'] = '豹纹迷彩',
    ['component_camo_finish8'] = '斑马迷彩',
    ['component_camo_finish9'] = '几何迷彩',
    ['component_camo_finish10'] = '繁荣迷彩',
    ['component_camo_finish11'] = '爱国迷彩',
  
    ['component_camo_slide_finish'] = '数码幻灯片迷彩',
    ['component_camo_slide_finish2'] = '笔触滑动幻灯片迷彩',
    ['component_camo_slide_finish3'] = '林地幻灯片迷彩',
    ['component_camo_slide_finish4'] = '骷髅幻灯片迷彩',
    ['component_camo_slide_finish5'] = '六十九幻灯片迷彩',
    ['component_camo_slide_finish6'] = '泰迪幻灯片迷彩',
    ['component_camo_slide_finish7'] = '豹纹幻灯片迷彩',
    ['component_camo_slide_finish8'] = '斑马幻灯片迷彩',
    ['component_camo_slide_finish9'] = '几何幻灯片迷彩',
    ['component_camo_slide_finish10'] = '繁荣幻灯片迷彩',
    ['component_camo_slide_finish11'] = '爱国幻灯片迷彩',
  
    ['component_clip_default'] = '默认弹夹',
    ['component_clip_extended'] = '加长弹夹',
    ['component_clip_drum'] = '圆形弹鼓',
    ['component_clip_box'] = '盒形弹鼓',
  
    ['component_scope_holo'] = '全息瞄准镜',
    ['component_scope_small'] = '低倍镜',
    ['component_scope_medium'] = '中倍镜',
    ['component_scope_large'] = '高倍镜',
    ['component_scope'] = '狙击镜',
    ['component_scope_advanced'] = '高倍瞄准镜',
    ['component_ironsights'] = '机瞄',
  
    ['component_suppressor'] = '消音器',
    ['component_compensator'] = '补偿器',
  
    ['component_muzzle_flat'] = '扁平枪口制动器',
    ['component_muzzle_tactical'] = '战术枪口制动器',
    ['component_muzzle_fat'] = '圆形枪口制动器',
    ['component_muzzle_precision'] = '精密枪口制动器',
    ['component_muzzle_heavy'] = '重型枪口制动器',
    ['component_muzzle_slanted'] = '倾斜的枪口制动器',
    ['component_muzzle_split'] = '分体式枪口制动器',
    ['component_muzzle_squared'] = '方形枪口制动器',
  
    ['component_flashlight'] = '战术手电筒',
    ['component_grip'] = '握把',
  
    ['component_barrel_default'] = '默认枪管',
    ['component_barrel_heavy'] = '重型枪管',
  
    ['component_ammo_tracer'] = '追踪弹药',
    ['component_ammo_incendiary'] = '燃烧弹药',
    ['component_ammo_hollowpoint'] = '空心弹药',
    ['component_ammo_fmj'] = 'FMJ 弹',
    ['component_ammo_armor'] = '穿甲弹',
    ['component_ammo_explosive'] = '穿甲燃烧弹',
  
    ['component_shells_default'] = '默认弹',
    ['component_shells_incendiary'] = '龙息弹',
    ['component_shells_armor'] = '钢制铅弹',
    ['component_shells_hollowpoint'] = '空尖弹',
    ['component_shells_explosive'] = '空爆弹',
  
    -- 武器子弹
    ['ammo_rounds'] = '发(子弹)',
    ['ammo_shells'] = '发(子弹)',
    ['ammo_charge'] = '喷',
    ['ammo_petrol'] = '加仑(燃料)',
    ['ammo_firework'] = '发(烟花弹)',
    ['ammo_rockets'] = '枚(火箭弹)',
    ['ammo_grenadelauncher'] = '发(榴弹)',
    ['ammo_grenade'] = '枚(手榴弹)',
    ['ammo_stickybomb'] = '枚(炸弹)',
    ['ammo_pipebomb'] = '枚(炸弹)',
    ['ammo_smokebomb'] = '枚(炸弹)',
    ['ammo_molotov'] = '瓶(汽油瓶)',
    ['ammo_proxmine'] = '个(地雷)',
    ['ammo_bzgas'] = '罐',
    ['ammo_ball'] = '个(球)',
    ['ammo_snowball'] = '个(雪球)',
    ['ammo_flare'] = '根(信号棒)',
    ['ammo_flaregun'] = '发(信号弹)',
    
    -- 武器涂装
    ['tint_default'] = '默认色调',
    ['tint_green'] = '绿色调',
    ['tint_gold'] = '金色调',
    ['tint_pink'] = '粉色调',
    ['tint_army'] = '军用色调',
    ['tint_lspd'] = '洛圣都警局色调',
    ['tint_orange'] = '橙色调',
    ['tint_platinum'] = '铂金色调',
    
    -- 职责相关
    ['stopped_duty'] = '你已停止履行职责.',
    ['started_duty'] = '你已经开始你的职责了.',
  }

**Comment by iSentrie** [comment]
make a pull request

**Comment by Benzo00** [comment]
make a pull request
