### ISSUE TITLE
Ls Custom

### ISSUE THREAD

**Issue by frazz1234** [esx-framework/esx-legacy#328]
Hey! im not getting all the modfication i could get for a car

The dashboard is a good exemple ! Im using the vMenu and i have lot more thing i can do! 

someone can help ?

**Comment by iSentrie** [comment]
dashboard color
interior color
drift tyres
wheel size
wheel width
custom tires
plates (few missing)
extras
... might be more

**Comment by frazz1234** [comment]
Yeah right ! We should modify no? 

Team ESX let's do it !

**Comment by Benzo00** [comment]
i really dont understand what you mean 🤔

**Comment by frazz1234** [comment]
🤷‍♂️ apparently the other person understands what I mean.

Use vMenu and compare the differences between the ESX lscustom. Missing a lot of modification

**Comment by Benzo00** [comment]
if u want to suggest something to be added please do a list of exactly what needs to be added and explain why

**Comment by frazz1234** [comment]
iSentrie just expose you some missing modification on the script
