### ISSUE TITLE
es_extended Config.DisableVehicleRewards & Config.DisableNPCDrops doesnt work

### ISSUE THREAD

**Issue by ofcshiro** [esx-framework/esx-legacy#330]
Both Config options dont work.

  if Config.DisableNPCDrops then
    RemoveAllPickupsOfType(0xDF711959) -- carbine rifle
    RemoveAllPickupsOfType(0xF9AFB48F) -- pistol
    RemoveAllPickupsOfType(0xA9355DCD) -- pumpshotgun
  end

and 

if Config.DisableVehicleRewards then
    DisablePlayerVehicleRewards(PlayerId())
end

have to be in a loop in order to work

**Comment by Slewog** [comment]
Yeap need to be runned every frame
