### ISSUE TITLE
[Bug] - es_extended - updateWeaponAmmo

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#362]
**Describe the bug**
Event overflow while pouring gas.

**To Reproduce**
1. Get `weapon_petrolcan`
3. Pour it non stop
4. If gas can is full then after about half of it poured player will get event overflow
6. Reliable network event overflow.

https://user-images.githubusercontent.com/29688478/181214923-05148d1d-f9f8-42d7-9485-5df97712d965.mp4

**Comment by Mycroft-Studios** [comment]
Should be fixed now
