### ISSUE TITLE
esx_status server/main.lua FIX

### ISSUE THREAD

**Issue by HumanTree92** [esx-framework/esx-legacy#37]
Error: SCRIPT ERROR: @esx_status/server/main.lua:58: attempt to index a nil value (global 'status')

On line 56 Change
```lua
AddEventHandler('esx_status:getStatus', function(playerId, statusName, cb)
	for i=1, #ESX.Players, 1 do
		if status[i].name == statusName then
			cb(status[i])
			break
		end
	end
end)
```

to

```lua
AddEventHandler('esx_status:getStatus', function(playerId, statusName, cb)
	local xPlayer = ESX.GetPlayerFromId(playerId)
	local status = xPlayer.get('status')

	for i=1, #status, 1 do
		if status[i].name == statusName then
			cb(status[i])
			break
		end
	end
end)
```

Unless there is another way to get the status of a player but when i try to use esx_policejobs to check a player there error above is what i get.

**Comment by konijn-x** [comment]
Hi, nice that you want to help the framework, but to propose a change, you should better use the Pull Request tab.

**Comment by PsychoShock** [comment]
I have add it in https://github.com/esx-framework/esx-legacy/pull/70/commits/848af41dfff1f98d8018b2e261330253e5dfdbc0 you can close this, thanks @HumanTree92

**Comment by HumanTree92** [comment]
> I have add it in [848af41](https://github.com/esx-framework/esx-legacy/commit/848af41dfff1f98d8018b2e261330253e5dfdbc0) you can close this, thanks @HumanTree92

Thanks yeah. I forgot to do a Pull Request. At first i thought i was the only one having this issue. Which is why i didn't do the Pull Request.
