### ISSUE TITLE
[Bug] - esx_joblisting - menu doesn't close

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#372]
**Describe the bug**
Menu doesn't close when **2 or more** new zones added to the config. This happens menu player goes away with menu open and distance > than set.

**To Reproduce**
1. Add additional `Config.Zones location`
2. Go away from marker while menu open
3. Menu will not close

**Expected behavior**
Menu should close with multiple zones too.

**Comment by CsokiHUN** [comment]
fixed in #377

**Comment by Benzo00** [comment]
fixed, thanks @CsokiHUN
