### ISSUE TITLE
Translate esx_property, correct code style of esx_property

### ISSUE THREAD

**Issue by mcNuggets1** [esx-framework/esx-legacy#391]
For some unannounced reason, esx_property was replaced.
Sadly even it's english translation is extremely bad.
It is not supporting the default esx locale system and certainly not following any codestyle.

This resource just seems odd to be included with ESX and comes off as even pirated.
I didn't see any original author being marked or something like that.

And please for gods sake, why the hell is the codestyle 3 spaces instead of widely in ESX used tabs.

Also the removing of instance creates a bunch of problems, as it is used within a lot of paid and not paid resources.

Just improve the instance code and leave it int the codebase, as it should be, because of backwards compatibility.

You could for example use routing buckets for the different instances, instead of making something invisible/visible etc. as an example.
Just comes off as intransparent to make huge changes without a proper warning first and time, so developers can prepare.

**Comment by Mycroft-Studios** [comment]
> For some unannounced reason
This was announced several months ago and has been in a public beta for the last month.

**Comment by mcNuggets1** [comment]
1. Where?
2. Why not use the locale system of esx then? And why use 3 spaces contradicting the codebase.
3. Never heard of asset escrow huh? Also I don't do that. But even new resources use it.

Very arrogant response to some valid criticism.

**Comment by mcNuggets1** [comment]
Also why do you delete my second issue, which you still haven't fixed?

**Comment by mcNuggets1** [comment]
4.
It still is, it's still not working, I have it fixed on my end, but your version is still broken.
You changed "source", which was a vector to xPlayer.source which is a number in 2 instances, breaking the function.
Don't know how making it a callback fixed anything, it just worsens the situation, because callbacks are used in async loops and this isn't.

2.
And how do you have to spend hours making translations?
Just use the locale system, add the language english and let the community do the rest.
That's literally the point of the locale system integrated in ESX.

3.
That doesn't make any sense.
The instance resource is quite useful, if imporved.
Instead of copy & pasting code thousands of times, we could use the integrated instance system, but alright.

**Comment by Mycroft-Studios** [comment]
> Don't know how making it a callback fixed anything, it just worsens the situation, because callbacks are used in async loops and this isn't.

considering that code was originally using cb and then changed to return by me a few days ago

 2. because i have to make the starting template?
 
 3. why would u have a resource that just triggers a native lol 
 routing buckets and conceal natives and much better than the instance resource and rewriting the instance resource to use them would break the compatibility anyway

**Comment by mcNuggets1** [comment]
1. There's literally a function below that doesn't follow the same procedure and there's no reason to make it a callback, as stated.
IT IS NOT  async and it wasn't a callback before, I've used that function since the release of it and it never was.

3. If making a locale file and adding some strings is hours of work, I don't want to know what you are doing. If you release resources under a framework, they should follow the codebase, style and localisation of the rest of the codebase, that's common knowledge. Being lazy isn't an excuse for anything.

4. True, didn't see it that way.
