### ISSUE TITLE
[Bug] - esx_identity - no input validation on creation page 

### ISSUE THREAD

**Issue by itschip** [esx-framework/esx-legacy#395]
**Describe the bug**
Hi, some ux issue have occurred. When you create a new player, there no input validation for names. I learned the hard way that it needs to start with a capital letter. 

**To Reproduce**
1. Start the server
2. Open fivem
3. load into the server
4. add a name without a captial letter to start with

**Expected behavior**
I want to an error

**Screenshots**

**Comment by Benzo00** [comment]
will fix this :)

**Comment by Benzo00** [comment]
this should now be fixed :)
