### ISSUE TITLE
[Bug] - es_extended - onesync vehicles spawning

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#400]
While spawning vehicles and there is other players nearby, it might spawn you a vehicle with random plates.

**To Reproduce**
1. Try spawn an vehicle, ex. from esx_policejob or any other...
2. Get any other player to stay nearby while you spawn vehicles
3. Sometimes it can fail and you will get a vehicle with random plates

This happens very often, usually on first tries like 1-3 it can spawn as it suppose, but after that it most likely always fail to set correct plates, maybe tuning too... This doesn't happen if there is no other players around.

ESX version: 1.7.5 (source code)

**Comment by mahanmoulaei** [comment]
This could be fixed by requesting control over the entity before applying vehicle properties.

**Comment by thelindat** [comment]
> fixed by requesting control over the entity

No, you tell the owner to do the tasks. Don't use request control natives.

**Comment by mr-capy** [comment]
I am still having this issue in latest while from esx_garages not the latest but old ... Before stable version of extended 1.7.5 was working fine but today i downloaded latest one it creating issue like when spawn vehicle it give vehicle random plate sometime and sometime it give correct plate

**Comment by mr-capy** [comment]
I am still having this issue in latest while from esx_garages not the latest but old ... Before stable version of extended 1.7.5 was working fine but today i downloaded latest one it creating issue like when spawn vehicle it give vehicle random plate sometime and sometime it give correct plate

**Comment by iSentrie** [comment]
issue still persists, random plates and random liveries

**Comment by mr-capy** [comment]
So thats why i downgrade but when i down grade the property not work coz of context menu ... But i add context menu and everything to stable version still property system not working

**Comment by mr-capy** [comment]
Someone should do it ASAP coz vehicle with random plate is a major issue and liveries too

**Comment by mahanmoulaei** [comment]
> So thats why i downgrade but when i down grade the property not work coz of context menu ... But i add context menu and everything to stable version still property system not working. 

_For property system, try to change the json file name to anything different(e.g. database.json) and also replace the occurrences of 'properties.json' with "TheFileNewName.json" in server-side. I have no idea how the hell that is a solution, but it fixed the issue of property system not saving data onResourceStop._
