### ISSUE TITLE
[Bug] - esx_property - Issue

### ISSUE THREAD

**Issue by ofcshiro** [esx-framework/esx-legacy#409]
**Describe the bug**
If you dont use Realestate and you press F6 you still get the Realestate Action Menu (even if you dont have the job) 

![image](https://user-images.githubusercontent.com/105174877/185769059-6b0701ea-b71e-4f9a-8ebc-87b0bb809fd0.png)

**To Reproduce**
1. Go on the Server
2. Give you any Job
3. Press F6

**Expected behavior**

**Screenshots**

**Debug Info (please complete the following information):**
 - OS: Windows Server 2019 
 - FiveM Artifact : 5815
 - ESX Version: 1.7.5 (Property downloaded 5 mins ago) 

**Additional context**
The Screenshot i submitted shows, that i am a Police Officer and that the Realestate Menu opens
even if its empty it interfers with any other "Action Menu"

**Comment by Mycroft-Studios** [comment]
this is intended behaviour, since your an admin, tho the real bug is that u cannot see the options 👁️
