### ISSUE TITLE
[Bug] - es_extended - addAccountMoney / removeAccountMoney rounding

### ISSUE THREAD

**Issue by Mojito-Fivem** [esx-framework/esx-legacy#421]
**Describe the bug**
xPlayer.addAccountMoney and xPlayer.removeAccountMoney rounds the amount of money

**To Reproduce**
1. xPlayer.addAccountMoney with floating point value and you get the nearest integer

**Expected behavior**
esx gives the player the amount of account money specified.

**Debug Info (please complete the following information):**
 - OS: Uwubuntu 20.04 LTS Server
 -  FiveM Artifact: Latest Recommended 
 - ESX Version: Latest legacy

**Comment by Mycroft-Studios** [comment]
fixed this, will be pushed soon :)
