### ISSUE TITLE
Not sure bug just not sure where this is coming from

### ISSUE THREAD

**Issue by kelevra69** [esx-framework/esx-legacy#425]
I tired looking around for the answer but could not find it.  Thanks for whoever tells me.  Its the default put on clothes menu.  Its using the K key and I want to stop it from running.  Anyone tell me what script is running this thanks!!

**Comment by Benzo00** [comment]
https://github.com/esx-framework/esx-legacy/blob/78702eda81a7ddc1c98b8800e80756e1d231120f/%5Besx_addons%5D/esx_accessories/client/main.lua#L237

**Comment by Benzo00** [comment]
as u see in the link i posted, its in esx_accessories :)

**Comment by kelevra69** [comment]
TY
