### ISSUE TITLE
Cant choose or change livery and GTA cars

### ISSUE THREAD

**Issue by EcstasyX** [esx-framework/esx-legacy#426]
**Describe the bug**
Cannot change or apply a livery to GTA CArs
**To Reproduce**
1. Go to 'Ls Customs'
2. Click on 'Stickers'
3. Scroll down to 'any of the liveries'
4. See error no errors just doesnt change anything

**Expected behavior**
should be changing the liveries as i go through the list

**Screenshots**

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux) windows
 -  FiveM Artifact 5562
 - ESX Version: 1.7.2

**Additional context**

**Comment by mr-capy** [comment]
It was work fine in older extended 1.7.5 the stable version released its broken in updates somehow

**Comment by Mycroft-Studios** [comment]
this was broken by R* changing natives around, will be fixed soon

**Comment by EcstasyX** [comment]
Just Updated Es_Extended and its working now, thanks Mycroft and Team. You guys are the best!
