### ISSUE TITLE
fix Error Missing Create Pickup 

### ISSUE THREAD

**Issue by Rungrot444** [esx-framework/esx-legacy#427]
goto es_extended/client/main.lua 
Line:369

TriggerEvent('esx:createPickup', pickupId, pickup.label, pickup.coords - vector3(0,0, 1.0), pickup.type, pickup.name, pickup.components, pickup.tintIndex)

TO

TriggerEvent('esx:createPickup', pickupId, pickup.label, vector3(pickup.coords.x, pickup.coords.y, pickup.coords.z), pickup.type, pickup.name, pickup.components, pickup.tintIndex)

**Comment by Mycroft-Studios** [comment]
you could, PR, the fix
