### ISSUE TITLE
[Bug] - esx_jobs - Issue

### ISSUE THREAD

**Issue by mindkind** [esx-framework/esx-legacy#435]
[   4663516] [b2545_GTAProce]             MainThrd/ __Lua_InvokeNative: execution failed: Argument at index 1 was null.
[   4663516] [b2545_GTAProce]             MainThrd/ ^1SCRIPT ERROR: Execution of native 0000000032ca01c3 in script host failed: Argument at index 1 was null.^7
[   4663516] [b2545_GTAProce]             MainThrd/ ^3> AddTextEntry^7 (^5AddTextEntry.lua^7:3)
[   4663516] [b2545_GTAProce]             MainThrd/ ^3> ref^7 (^5@es_extended/client/functions.lua^7:128)
[   4663516] [b2545_GTAProce]             MainThrd/ ^3> fn^7 (^5@esx_jobs/client/main.lua^7:442)
[   4663516] [b2545_GTAProce]             MainThrd/ ^1SCRIPT ERROR: error object is not a string^7

**Comment by mindkind** [comment]
When i spawn the car

**Comment by mindkind** [comment]
i have changed the line 440 for this one
if (onDuty or zone.Type == "cloakroom") and zone.Type ~= "vehdelete" and zone.Type ~= "vehspawnpt" then

**Comment by mindkind** [comment]
it was updated to the last version

**Comment by mindkind** [comment]
the line 440 is still not fix with my pull request so the error is still there

**Comment by Benzo00** [comment]
esx_jobs getting a full rewrite!
