### ISSUE TITLE
[Bug] - esx_jobs - Can't use teleport at Arcadius Building

### ISSUE THREAD

**Issue by highclassacts** [esx-framework/esx-legacy#443]
**Describe the bug**
While attempting to use the green marker at the Arcadius Building in Pillbox Hill, I received this error: 
[    164406] [b2372_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @es_extended/client/functions.lua:422: attempt to index a nil value (local 'coords')^7
[    164406] [b2372_GTAProce]             MainThrd/ ^3> ref^7 (^5@es_extended/client/functions.lua^7:422)
[    164406] [b2372_GTAProce]             MainThrd/ ^3> fn^7 (^5@esx_jobs/client/main.lua^7:364)
[    164406] [b2372_GTAProce]             MainThrd/ ^1SCRIPT ERROR: error object is not a string^7

**To Reproduce**
1. Go to the green marker at the Arcadius Building.
2. Walk into the marker. The error should be in the console.

**Expected behavior**
I was hoping to use the marker to teleport to the building's roof.

**Screenshots**
N/A

**Debug Info (please complete the following information):**
 - OS: Windows 10 
 -  FiveM Artifact: 5837
 - ESX Version: The version that was available at 12:05am EST on September 6th, 2022

**Additional context**
No additional context.

**Comment by highclassacts** [comment]
Update: I have another marker near the green one that I mentioned that is from another script that I use for teleporting. Since the green one made by esx_jobs doesn't work, I am actually unsure as to what it's function is, but trying to activate it by pressing E triggers the error posted in my original post. Sorry for any confusion.

**Comment by tony-stark-17** [comment]
https://github.com/esx-framework/esx-legacy/pull/444

**Comment by Benzo00** [comment]
merged tonys pr
