### ISSUE TITLE
[Bug] - esx_policejob - Issue

### ISSUE THREAD

**Issue by JotaPe69** [esx-framework/esx-legacy#449]
**Describe the bug**
Error on F8

**To Reproduce**
I just restarted the script and saw the error on F8.

**Screenshots**
![image](https://user-images.githubusercontent.com/112979809/188720617-24038721-b346-478b-9dd2-f35bf5a7cd9b.png)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact: 5848
 - ESX Version: Legacy 1.7.5

**Comment by katakume-bixbi** [comment]
Update your es_extended

**Comment by GRZ-D3V** [comment]
This can be closed. ESX updated:
![image](https://user-images.githubusercontent.com/60541417/188721746-61bb79aa-c8f6-4442-883b-2c9d52d53617.png)
