### ISSUE TITLE
[Bug] - es_extened - Issue Weapon attachments 

### ISSUE THREAD

**Issue by xd-vape** [esx-framework/esx-legacy#453]
**Describe the bug**
since 1.7.5 it is not possible to buy weapon attachments anymore, only errors occur and the attachments appear on the weapon only after the server restart

**Expected behavior**
that the component appears on my weapon and that this is then saved directly

**Debug Info (please complete the following information):**
 - OS: Linux
 - FiveM Artifact: Latest
 - ESX Version: 1.7.5

**Additional context**
Here is the Error code that i get when i try to add a attatchment
`[  script:es_extended] SCRIPT ERROR: @es_extended/server/classes/player.lua:384: bad argument #1 to 'joaat' (string expected, got table)

[  script:es_extended] > ref (@es_extended/server/classes/player.lua:384)

[  script:es_extended] > ref (@esx_policejob/server/main.lua:344)

[  script:es_extended] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:479: attempt to concatenate a nil value (local 'err')

[  script:es_extended] 
[  script:es_extended] > TriggerServerCallback (@es_extended/server/functions.lua:172)

[  script:es_extended] > handler (@es_extended/server/common.lua:110)`

**Comment by xd-vape** [comment]
due to the fact that this bug exists for example the police job does not work properly

**Comment by MacHunt** [comment]
Fix is very simple...
es_extended --> server --> classes -- > player.lua
Replace function called **self.addWeaponComponent** with this.
```
function self.addWeaponComponent(weaponName, weaponComponent)
		local loadoutNum, weapon = self.getWeapon(weaponName)

		if weapon then
			local component = ESX.GetWeaponComponent(weaponName, weaponComponent)

			if component then
				if not self.hasWeaponComponent(weaponName, weaponComponent) then
					self.loadout[loadoutNum].components[#self.loadout[loadoutNum].components + 1] = weaponComponent
					local componentHash = ESX.GetWeaponComponent(weaponName, weaponComponent).hash
					GiveWeaponComponentToPed(GetPlayerPed(self.source), joaat(weaponName), componentHash)
					self.triggerEvent('esx:addInventoryItem', component.label, false, true)
				end
			end
		end
	end
```

**Comment by xd-vape** [comment]
OMG thank you! you fix my problem!!
