### ISSUE TITLE
esx_taxijob - can have open stocks menu anywhere in world

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#46]
https://github.com/esx-framework/esx-legacy/blob/8153f6a9221baeef0affb0176e5811007b8f5e3b/%5Besx_addons%5D/esx_taxijob/client/main.lua#L367

Allows players to have open storage menu and fast/transfer/sell goods to anywhere they go.

repro:
1. put something in to storage
2. quickly start walking from the point
3. menu will reopen outside of checkpoint and it won't close

**Comment by PsychoShock** [comment]
This is not really a issue, you can make a thread when player open the menu and close it if `dist > 3.0` or something like that.
