### ISSUE TITLE
[Bug] - fresh server - Issue

### ISSUE THREAD

**Issue by hasidu** [esx-framework/esx-legacy#469]
**Describe the bug**
i installed fresh esx 20 min ago but its give me this erorr on esx notify
![image](https://user-images.githubusercontent.com/72035642/190513815-2ea80d93-283a-4127-9dcb-7b3741b2d3bb.png)

**Expected behavior**
i went to the server to creat my ped but sfter i create identity server gave me esx_notify errors

**Screenshots**
![image](https://user-images.githubusercontent.com/72035642/190513815-2ea80d93-283a-4127-9dcb-7b3741b2d3bb.png)

**Debug Info (please complete the following information):**
 - OS: ( Windows)
 -  FiveM Artifact
 - ESX Version: new freash from tx admin

**Comment by Benzo00** [comment]
now fixed :)

**Comment by Benzo00** [comment]
https://github.com/esx-framework/esx-legacy/commit/33121de445e980efd3c66d6e9c127a9270fa9cf3 this should have fixed it
