### ISSUE TITLE
Fraction Garage

### ISSUE THREAD

**Issue by akiilles05** [esx-framework/esx-legacy#472]
Hi! I have a problem that when the fraction is out of the garage it doesn't change to not being in the garage so no matter how many times I take it out. It will transfer it to SQL but it is still wrong.

**Comment by Mycroft-Studios** [comment]
?

**Comment by akiilles05** [comment]
You can take the car out of the police garage as many times as you like.

**Comment by akiilles05** [comment]
You can take the car out of the police garage as many times as you like.

**Comment by coresync2k** [comment]
u used the latest ox mysql?
