### ISSUE TITLE
[Bug] - es_extended - Issue

### ISSUE THREAD

**Issue by GittaGoat** [esx-framework/esx-legacy#487]
**Attachements don't work.**
When i spawn attachements with the command, the don't show up and give an error. After a restart it is on the weapon.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/1010658821309468722/1021491885530947744/unknown.png)

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux) Linux VPS
 - FiveM Artifact Latest
 - ESX Version: 1.85

**Comment by Mycroft-Studios** [comment]
already fixed
