### ISSUE TITLE
[Bug] - es_extended - Issue

### ISSUE THREAD

**Issue by maxcamorra** [esx-framework/esx-legacy#489]
**Describe the bug**
error in console

[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:330: attempt to index a nil value (local 'xPlayer')
[  script:es_extended] > handler (@es_extended/server/main.lua:330)
[  script:es_extended] > routeMessage (@chat/sv_chat.lua:187)
[  script:es_extended] > handler (@chat/sv_chat.lua:218)

**Comment by Benzo00** [comment]
?? when does this happen? can u give some more info besides a error message??

**Comment by maxcamorra** [comment]
I dont know when this exactly happens :D i just saw it inside the console and sent it here maybe it will help something but also could be someone calling a chat without being a player i dont know :D

**Comment by Mycroft-Studios** [comment]
user issue caused by not reading the docs
