### ISSUE TITLE
Admin Group order

### ISSUE THREAD

**Issue by SamilWilson** [esx-framework/esx-legacy#51]
Hi, my problem is that I want to create my own groups such as supporters or superadmin. But the problem is, when I give myself the group, the admin rank is always at the top. I would make it so that the top tier is superadmin and then admin and so on. but admin remains the highest rank all the time and I don't know how to change that ...

My Order that i want to have:
highest group: 
superadmin
admin
mod
supporter
guide

The Order that i have now
highest group: 
admin
...

I don't even know if supporter is higher than guide or the other way around

**Comment by Mycroft-Studios** [comment]
ESX has the `superadmin` group Disabled.

To add more groups, you use the built In FiveM Ace-Perms

**Comment by djbrunoatimix** [comment]
Hello guys, I have tried to figure out how to create new Groups through FiveM Ace-Perms but I was unable to do it. @Mycroft-Studios could you give some examples of where we should add the ace line and how is this line supposed to be ?
