### ISSUE TITLE
nill value "coords"

### ISSUE THREAD

**Issue by BattleStar247** [esx-framework/esx-legacy#54]
i have a problem where players spawn randomly on the map instead of last potition.
i get an error on f8 saying es_extended nill value "Coords" at line 26 if i can recall. i am not home right know but i will update.
 any guess ? jsut noticed there is already a "issue report at #52. exact same problem. i guess it cant load coords and thats why i random spawn. maybe conected maybe not

**Comment by BattleStar247** [comment]
seems like deleting "[gamemodes]" folder including "basic-gamemode" and "[maps]" fixed the problem for me

**Comment by Roydeking52** [comment]
Thats correct the readme says tot remove it.
