### ISSUE TITLE
[Bug] - script:oxmysql error

### ISSUE THREAD

**Issue by ineokb** [esx-framework/esx-legacy#548]
Hello, I have this error that persists.
Someone who could help me? I just installed the server and I did not touch anything I updated but the error remains.
Thanks, have a good day

**Expected behavior**
[ script:esx_property] [INFO] Adding Property into datastore table
[ script:esx_property] [INFO] Adding Property into datastore_data table
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: esx_property was unable to execute a query!
[      script:oxmysql] Erreur de syntaxe près de 'IF NOT EXISTS `last_property` LONGTEXT NULL' à la ligne 1
[      script:oxmysql] ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `last_property` LONGTEXT NULL []
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:22257)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] > async rawQuery (@oxmysql/dist/build.js:22224)
[      script:oxmysql]
[      script:webpack] chat: built webpack.config.js

**Screenshots**
![image](https://user-images.githubusercontent.com/44065363/194542954-8ac15712-c51b-4764-a4af-b3a6c250b024.png)

 - OS:  Windows
 -  FiveM Artifact latest
 - ESX Version: LEGACY 1.8.5

**Comment by Gellipapa** [comment]
Hi! Remove users table last_property field if exist or remove users table and restart server. I tested this query and i don't get errors. I think query is good.

**Comment by ineokb** [comment]
The worries remain the same.
Even by deleting from the base when I launch the cmd the error comes back when it no longer exists in the database

**Comment by B1ack3ye** [comment]
> Hi! Remove users table last_property field if exist or remove users table and restart server. I tested this query and i don't get errors. I think query is good.

I have a setup with MySQL and i get errors with this query:
```
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `last_property` LONGTEXT NULL
```
![image](https://user-images.githubusercontent.com/63259739/195375673-4f6f1a90-b76b-4d99-b75d-951e23ac73d8.png)

This Query dont work in MySQL version 8.30+

This problem is not fixed in the new version!

**Comment by Gellipapa** [comment]
@B1ack3ye Hi! Try MariaDB so should works.

**Comment by holyschytt** [comment]
Remove IF NOT EXISTS its no longer supported
ALTER TABLE `users` ADD COLUMN `last_property` LONGTEXT NULL
