### ISSUE TITLE
Cam View

### ISSUE THREAD

**Issue by schenker899** [esx-framework/esx-legacy#550]
Hello, we have found with us with ESX 1.7.5 and ESX 1.8.5 fresh installation that the camara keeps bugging.

the view is stuck in the normal position instead of the close view.

[Pic 1](https://imgur.com/tL8crNE)
[Pic 2](https://imgur.com/7NNpcnn)

**Comment by Benzo00** [comment]
remake this issue with more information please.. cant do much with only this info
