### ISSUE TITLE
[Bug] - esx_policejob - Issue

### ISSUE THREAD

**Issue by Midnight-Vortex** [esx-framework/esx-legacy#558]
**Describe the bug**
Vehicle Interaction not work.

**To Reproduce**
1. Press key for policejob menu
2. Goto vehicle interaction
3. See error f8

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44612764/195521372-395d4f4c-0e39-491a-9868-e4f3afcc94e5.png)

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact - 5914
 - ESX Version: 1.8.5

**Comment by Benzo00** [comment]
please post a screenshot that we dont have to download..

**Comment by Midnight-Vortex** [comment]
![grafik](https://user-images.githubusercontent.com/44612764/195521408-21a1ce77-6075-45cc-8511-334339e07bc7.png)

**Comment by Benzo00** [comment]
so esx_policejob is getting a full remake. and will probably be out this week, due to this i will close the issue since we wont fix any issues since a new better policejob is on the way, hopefully done this week like i said!
