### ISSUE TITLE
[Bug] - es_extended - Giving Weapons

### ISSUE THREAD

**Issue by JaviX7X** [esx-framework/esx-legacy#560]
**Describe the bug**
When using the giveweapon command, it shows up as you've been given the weapon, but when you actually open the weapon wheel, nothing shows up.

**To Reproduce**
1. Use command /giveweapon (ID) (WEAPON_NAME) (ammo)
2. See that your weapon has been given
3. Open your weapon wheel, and nothing appears
4. Use /clearloadout (ID), and you'll the the "- WEAPON_NAME message"

**Expected behavior**
They weapon should be added

**Screenshots**
[Clip](https://cdn.discordapp.com/attachments/1008401371122372789/1029075636255477780/2022-10-10_18-57-54.mp4)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact 5848
 - ESX Version: Legacy 1.8.5 (latest)

**Additional context**
If I download the release version of ESX legacy 1.7.5, it works perfectly

**Comment by iSentrie** [comment]
tbh it works fine for me, i use it almost everyday with 1.8.5

**Comment by AstroNext** [comment]
Give weapon works fine for me in version 1.8.5.
Please check your onesync that is on with legacy.
