### ISSUE TITLE
esx_holdup issue

### ISSUE THREAD

**Issue by timonation** [esx-framework/esx-legacy#57]
esx_holdup dont works on this legacy esx version. i cant rob. no errors. no notify in circle that can  rob this. cops set to 0 to test. same isue

**Comment by karthik-pitchai03** [comment]
if distance < 0.5 then -- change this in client/main.lua line 91 to if distance < 1.5 then

also you need to be armed

**Comment by Naifen-Phoxidas** [comment]
Works with the solution from @karthik-pitchai03 ?

**Comment by x0Z3ro0x** [comment]
You'll need to raise the markers in the configuration file. I had to do the same thing as they are in the ground and unable to be triggered. Raising them allowed it to be triggered. The car dealership boss menu has a similar issue. I'm actually online now fixing this very thing and will post here to a pull request when I'm done. You can wait for me or do it yourself.

**Comment by timonation** [comment]
ok  im waiting thx
