### ISSUE TITLE
[Bug] - esx_lscustom - Error in client console

### ISSUE THREAD

**Issue by INikYTI** [esx-framework/esx-legacy#579]
Description:
Hey, when i am at the tuning point and i want to select the standard option, i get a error in the F8 client console.

Reproduce:
1. Go tuning
2. Press [E]}
3. Go to "upgrades"
4. Select one option 
5. Choose "Standard"
6. Console prints the error

Expected behavior:

- Standard should be selected

Debug Info:
 - OS: Linux
 -  FiveM Artifact: 5956 
 - Game Build: 2699
 - ESX Version: 1.8.5

Screenshots are attached.
![Screenshot_1](https://user-images.githubusercontent.com/67703520/196434564-b98739f8-a776-4425-970c-6cc2e10919fc.png)
![Screenshot_2](https://user-images.githubusercontent.com/67703520/196434571-d98983a4-f726-4899-990f-959533069635.png)

**Comment by ThatPool** [comment]
**es_extended > locale.lua**
_Change:_
```
function TranslateCap(str, ...) -- Translate string first char uppercase
	return _(str, ...):gsub("^%l", string.upper)
end
```
_To:_
```
function TranslateCap(str, ...) -- Translate string first char uppercase
	local s,_ = _(str, ...):gsub("^%l", string.upper)
	return s
end
```

**esx_lscustom > client > main.lua**
_Change:_
`if data.current.label == TranslateCap('by_default') or string.match(data.current.label, TranslateCap('installed')) then`
_To:_
`if data.current.label == (" "..TranslateCap('by_default')) or string.match(data.current.label, TranslateCap('installed')) then`
