### ISSUE TITLE
Database Error from es_extended query

### ISSUE THREAD

**Issue by x0Z3ro0x** [esx-framework/esx-legacy#58]
**Describe the bug**
A database error on player login is produced to the console.

**To Reproduce**
Start the server and login.

**Screenshots / Logs**
```
[      script:hardcap] Connecting: x0Z3ro0x
[txAdmin:WebCtxUtils] [x0Z3ro0x] logged in via in-game ui
[  script:mysql-async] [MariaDB:10.6.5-MariaDB] [es_extended] [1ms] SELECT 1 FROM users WHERE identifier = 'EDITED'
[  script:es_extended] [INFO]  Player 1 Has been granted admin permissions via Ace Perms.
[  script:es_extended] SCRIPT ERROR: @mysql-async/lib/MySQL.lua:132: The SQL Query must be a string
[  script:es_extended] > execute (@mysql-async/lib/MySQL.lua:132)
[  script:es_extended] > createESXPlayer (@es_extended/server/main.lua:80)
[  script:es_extended] > ref (@es_extended/server/main.lua:57)
[  script:es_extended] > <unknown> (@mysql-async/mysql-async.js:15916)
[  script:mysql-async]
```

**Software:**
 - OS: Windows Server 2019
 - Version of the resource: Master Clone as of Yesterday Jan. 13th at 3pm.
 - Database Version MariaDB 10.6.5 (Also tried this on MySQL 8)

**Additional context**
I am able to change the error when I change my connection string. For example, if I use my old connection string from years ago, I can change the error into the following -

```
[      script:hardcap] Connecting: x0Z3ro0x
[txAdmin:WebCtxUtils] [x0Z3ro0x] logged in via in-game ui
[  script:mysql-async] SCRIPT ERROR in call ref: TypeError: Cannot read properties of null (reading 'execute')
[  script:mysql-async] > Object.callback (@mysql-async/mysql-async.js:5144)
[  script:mysql-async] > fetchScalar (@mysql-async/lib/MySQL.lua:161)
[  script:mysql-async] > onPlayerJoined (@es_extended/server/main.lua:52)
[  script:mysql-async] > handler (@es_extended/server/main.lua:41)
[  script:mysql-async]
[  script:es_extended] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:841: An error occurred while calling export mysql_fetch_scalar of resource mysql-async
[  script:es_extended] nil
[  script:es_extended] (nil stack trace)[txAdmin:WebCtxUtils] x0Z3ro0x executing:  STOP SERVER
-> Quitting: Server shutting down (x0Z3ro0x).

[txAdmin:FXRunner] >> [9348] FXServer Exited.
[txAdmin:FXRunner] >> [9348] FXServer Closed. (code 1)
```

Following instructions and using the connection string in the server.cfg provided gives the error I reported above. I have other servers using the database without issue. I normally use MySQL, however I switched in an attempt to solve the error. It remained the same.

Here are those connection strings I mentioned:

Old one from years prior -
```
#set mysql_connection_string "server=localhost;port=EDITED;database=es_extended;userid=EDITED;password=EDITED;ssl=none;charset=utf8mb4"
```

Current one provided from this github -
```
set mysql_connection_string "mysql://EDITED:EDITED@localhost/es_extended?waitForConnections=true&charset=utf8mb4"
```

If I've left out something important, it wasn't on purpose. Let me know and I will be happy to provide a log / information.

**Comment by x0Z3ro0x** [comment]
It's also worth noting this is on 5212 Artifact for FiveM. This was produced on a blank server with just the ESX Legacy installs.

**Comment by Naifen-Phoxidas** [comment]
Use this string
`set mysql_connection_string "server=YourIPAdress;database=es_extended;userid=YourUserID;password=YourPassword"`

**Comment by x0Z3ro0x** [comment]
Same thing -

```
[      script:hardcap] Connecting: x0Z3ro0x
[txAdmin:WebCtxUtils] [x0Z3ro0x] logged in via in-game ui
[  script:mysql-async] [MariaDB:10.6.5-MariaDB] [es_extended] [1ms] SELECT 1 FROM users WHERE identifier = 'EDITED'
[  script:es_extended] [INFO]  Player 1 Has been granted admin permissions via Ace Perms.
[  script:es_extended] SCRIPT ERROR: @mysql-async/lib/MySQL.lua:132: The SQL Query must be a string
[  script:es_extended] > execute (@mysql-async/lib/MySQL.lua:132)
[  script:es_extended] > createESXPlayer (@es_extended/server/main.lua:80)
[  script:es_extended] > ref (@es_extended/server/main.lua:57)
[  script:es_extended] > <unknown> (@mysql-async/mysql-async.js:15916)
[  script:mysql-async]
```

**Comment by Naifen-Phoxidas** [comment]
Do you use mysql-async 3.3.0 ?
When not try this version

**Comment by x0Z3ro0x** [comment]
I have changed to the version you recommend and it solved the issue.

For anyone reading this into the future, you cannot use anything under 3.3.0 for this version of ESX. That was the solution here. Also take note on the string posted above, perhaps that helped solve the issue too, although I cannot say that for sure. It's most likely the mysql change that solved this.

Thanks for the speedy and accurate assistance @Naifen-Phoxidas
