### ISSUE TITLE
[Bug] - esx_clothesstore - can't save clothes

### ISSUE THREAD

**Issue by Zonatex** [esx-framework/esx-legacy#584]
Describe the bug
Hey, when i change my Clothes than i can't save it

Reproduce
1. Go to Clothesshop
2. Change Clothes
3. Save Clothes

Expected behavior
see the errors in the Console

**Screenshots**
![image](https://user-images.githubusercontent.com/67367410/197342239-e9728508-5ae5-4d68-88a1-e0ff352a7132.png)

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact:  5893
 - ESX Version: 1.8.5

**Comment by nutria22** [comment]
you need to fix esx_property i think

**Comment by tony-stark-17** [comment]
Can you show your datastore table in your DB

**Comment by AstroNext** [comment]
> Can you show your datastore table in your DB
I tag author to response datastore table
@Zonatex

**Comment by Zonatex** [comment]
![image](https://user-images.githubusercontent.com/67367410/198899173-8e0dc510-a14f-4124-b3eb-940c13b7928a.png)

**Comment by AstroNext** [comment]
> 

Send me datastore_data when name is propert you can use this query

_SELECT * FROM datastore_data WHERE datastore_data.name LIKE 'property' AND datastore_data.owner NOT LIKE ''_

@Zonatex

**Comment by Zonatex** [comment]
![image](https://user-images.githubusercontent.com/67367410/198951727-dfdc75b9-8152-4821-8971-3afc4d6d0801.png)

**Comment by AstroNext** [comment]
> ![image](https://user-images.githubusercontent.com/67367410/198951727-dfdc75b9-8152-4821-8971-3afc4d6d0801.png)

Thx for reply,
Remove all row of property with empty or null owner and delete these lines from esx_property resource then test again .
https://github.com/esx-framework/esx-legacy/blob/0eff876881cf7bd794d893df4020844bac4048e0/%5Besx_addons%5D/esx_property/server/main.lua#L114-L118

**Comment by Gellipapa** [comment]
Hi! @Zonatex. Did database table clear solve your problem?

**Comment by Rav3n95** [comment]
Since there is no feedback, ill close the issue as solved!
