### ISSUE TITLE
[Bug] - es_extended - giveweapon weapon_navyrevolver don't give any weapon 

### ISSUE THREAD

**Issue by hoeggi93** [esx-framework/esx-legacy#588]
**Describe the bug**
When i want to give out the weapon navyrevolver i don't get any weapon but in the user table the loadout data is set 
as {"WEAPON_NAVYREVOLVER":{"ammo":240}}. 

**To Reproduce**

1. install clean fxserver (v4.18.1 atop FXServer 5960)  with esx legacy.
2. open the chat menu and insert /giveweapon {user id} weapon_navyrevolver {ammo} 
3. no weapon in weapon wheel 
4. loadout for the sql user table is set correctly with navyrevolver

**Expected behavior**
weapon navyrevolver is given to ped 

**Debug Info (please complete the following information):**
 - OS: ( Linux)
 -  FiveM ver. 5848
 - ESX Version: 160

**Comment by lexinor** [comment]
@hoeggi93 Quick question, did you try using the METAL_DETECTOR ?

**Comment by Benzo00** [comment]
this is not yet supported since its a new weapon i guess? i havent heard of this weapon before so if its from a new update then we will support it eventually.
