### ISSUE TITLE
Troubleshooting ESX Legacy Addons

### ISSUE THREAD

**Issue by x0Z3ro0x** [esx-framework/esx-legacy#59]
**Describe the bug**
New players are not given the esx_identity registration screen, or the esx_skin screen.

**To Reproduce**
Start the server and login as a new player with no database entry.

Screenshots / Logs
No errors are produced client or server side.

**Software:**
OS: Windows Server 2019
Version of the resource: Master Clone as of Jan. 13th at 3pm.
Database Version MariaDB 10.6.5

**Additional context**
Sadly I have no errors to provide making this harder to track down. When a new player logs into the server, they are placed at the job site as expected. However their mouse is stuck on the screen with no html window to register their name, age, etc.

Restarting the script esx_identity causes the html window to appear properly and then users can create their identity. However upon submitting, no skin window appears to then setup their character model. Restarting that along with the other resources that are shutdown as a result of the esx_skin restart, forces the esx_skin html window to popup for those new players and they can then create their skin.

I verified my load order to the letter. Aside from having extra startups, the orders are the exact same. Here is a copy -

```
# Server Prep

ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure rconlog
ensure scoreboard

ensure mysql-async
ensure cron
ensure skinchanger
ensure es_extended
ensure esx_menu_default
ensure esx_menu_dialog
ensure esx_menu_list
ensure esx_identity
ensure esx_skin

# ESX Scripts

#ensure esx_multicharacter   # es_extended requires Config.Multichar = true
ensure instance
ensure esx_rpchat
#ensure esx_phone
ensure esx_voice
ensure esx_sit
ensure esx_animations
ensure esx_addonaccount
ensure esx_addoninventory
ensure esx_datastore
#ensure esx_property
#ensure esx_garage
ensure esx_society
ensure esx_service
ensure esx_billing
ensure esx_license
ensure esx_dmvschool
ensure esx_status
ensure esx_basicneeds
ensure esx_optionalneeds
ensure esx_shops
ensure esx_weaponshop
ensure esx_clotheshop
ensure esx_barbershop
ensure esx_accessories
ensure esx_vehicleshop
#ensure esx_boat
ensure esx_jobs
ensure esx_joblisting
ensure esx_cruisecontrol
ensure esx_atm
#ensure esx_drugs
ensure esx_holdup
ensure esx_lscustom
#ensure esx_ambulancejob
#ensure esx_mechanicjob
#ensure esx_ambulancejob
#ensure esx_policejob
#ensure esx_bankerjob
#ensure esx_realestateagentjob
#ensure esx_taxijob
#ensure esx_whitelist

# Custom Scripts

#start DKGRP
start addon1
start addon2
start addon3
start addon4
start addon5
start addon6
start emergency
start nonemergency
```

**Comment by x0Z3ro0x** [comment]
Hey @thelindat just wanted to send a friendly shoutout to you. I noticed in the commit history that you have kicked some butt on esx_identity in the past. If you have some free time to take a look I would love a fresh set of eyes on this. No worries if you're busy I understand completely.

I've been trouble shooting this for a few days now. Messed around with the code a bit trying a few things I thought might be it to no success. Restarting the script gets the register menu to appear every time, however no skin menu shows up if you force restart esx_identity like that to get it's menu to appear.

The menu works at random. Out of about 20 tries to connect and get the register menu, we randomly had it twice. I thought perhaps it was my coding changes but testing ruled that out quickly when the menu no longer appeared after another disconnect, shutdown, and reconnect.

Either way I'll keep tinkering away.

**Comment by Luke20201** [comment]
> **Describe the bug** New players are not given the esx_identity registration screen, or the esx_skin screen.
> 
> **To Reproduce** Start the server and login as a new player with no database entry.
> 
> Screenshots / Logs No errors are produced client or server side.
> 
> **Software:** OS: Windows Server 2019 Version of the resource: Master Clone as of Jan. 13th at 3pm. Database Version MariaDB 10.6.5
> 
> **Additional context** Sadly I have no errors to provide making this harder to track down. When a new player logs into the server, they are placed at the job site as expected. However their mouse is stuck on the screen with no html window to register their name, age, etc.
> 
> Restarting the script esx_identity causes the html window to appear properly and then users can create their identity. However upon submitting, no skin window appears to then setup their character model. Restarting that along with the other resources that are shutdown as a result of the esx_skin restart, forces the esx_skin html window to popup for those new players and they can then create their skin.
> 
> I verified my load order to the letter. Aside from having extra startups, the orders are the exact same. Here is a copy -
> 
> ```
> # Server Prep
> 
> ensure mapmanager
> ensure chat
> ensure spawnmanager
> ensure sessionmanager
> ensure rconlog
> ensure scoreboard
> 
> ensure mysql-async
> ensure cron
> ensure skinchanger
> ensure es_extended
> ensure esx_menu_default
> ensure esx_menu_dialog
> ensure esx_menu_list
> ensure esx_identity
> ensure esx_skin
> 
> # ESX Scripts
> 
> #ensure esx_multicharacter   # es_extended requires Config.Multichar = true
> ensure instance
> ensure esx_rpchat
> #ensure esx_phone
> ensure esx_voice
> ensure esx_sit
> ensure esx_animations
> ensure esx_addonaccount
> ensure esx_addoninventory
> ensure esx_datastore
> #ensure esx_property
> #ensure esx_garage
> ensure esx_society
> ensure esx_service
> ensure esx_billing
> ensure esx_license
> ensure esx_dmvschool
> ensure esx_status
> ensure esx_basicneeds
> ensure esx_optionalneeds
> ensure esx_shops
> ensure esx_weaponshop
> ensure esx_clotheshop
> ensure esx_barbershop
> ensure esx_accessories
> ensure esx_vehicleshop
> #ensure esx_boat
> ensure esx_jobs
> ensure esx_joblisting
> ensure esx_cruisecontrol
> ensure esx_atm
> #ensure esx_drugs
> ensure esx_holdup
> ensure esx_lscustom
> #ensure esx_ambulancejob
> #ensure esx_mechanicjob
> #ensure esx_ambulancejob
> #ensure esx_policejob
> #ensure esx_bankerjob
> #ensure esx_realestateagentjob
> #ensure esx_taxijob
> #ensure esx_whitelist
> 
> # Custom Scripts
> 
> #start DKGRP
> start addon1
> start addon2
> start addon3
> start addon4
> start addon5
> start addon6
> start emergency
> start nonemergency
> ```

**Comment by Luke20201** [comment]
Hi @x0Z3ro0x,

I'm sorry you're experiencing this, I'll try and help you solve this issue.

### Firstly

Please verify you have inserted _all_ the SQL's to your database. This is quite a common cause for this!

### Secondly

Double-check both Client and Server Console for any error messages! There may be something appearing on the server-side (which could also point toward's Step One not being completed!) that you have missed.


If this hasn't worked for you, please answer the following question;
Are you using esx_mutlicharacter? If so, you have not uncommented it in the server.cfg. So this is probably the issue!

**Comment by x0Z3ro0x** [comment]
Yes all of my SQLs are imported. There is no errors, esx_multicharacter is commented out intentionally.

**Comment by x0Z3ro0x** [comment]
@Luke20201

I thought I might also mention that I am willing and capable of testing coding changes.

The UI is activating every time. Or at least I believe that to be the case due to the mouse being on screen and commenting out enableGUI stops the mouse and thus the UI from attempting to load.

That however is how far my limited knowledge has lead me. I believe it to be triggering 100% of the time, but for whatever reason, not properly displaying the HTML. I'm probably wrong. So if you have any ideas for me to try, Im happy to do so.

**Comment by Luke20201** [comment]
Hey, please try the following for me:

- Wipe your user's table of all rows
- Remove your esx_identity folder, then reinstall it using the latest version found in the repo
- Disable Deferrals in the identity config

If that does not work, please reply with an image of your users table - Purely so I can verify it has in fact been done correctly

**Comment by x0Z3ro0x** [comment]
Thanks for the suggestions,

I've done the first several times since posting the issue in an attempt to get the menu to trigger as characters saved don't get the dialog. Which is intended obviously. Haven't tried removing the resources and replacing it with one from here as this is a fresh install from this month on the 13th and the resource hasn't changed commits since then. However I am willing to give that a shot. Deferrals don't work. Users fail to load into the server with that turned on and thus has been disabled from day 1.

Here are the images you asked for -

[Table Setup](https://i.ibb.co/Tb7rWgK/Capture.png)

[Data](https://i.ibb.co/w0Vy69q/Capture.png)

**Comment by Luke20201** [comment]
Alright, everything looks good.
Do me a quick favor and put prints in every method, stating the method name. Then use that to find out where the method stops running.

**Comment by Luke20201** [comment]
Hey, try replacing client and server file's with this to Debug.
[esx_identity.zip](https://github.com/esx-framework/esx-legacy/files/7915543/esx_identity.zip)

**Comment by x0Z3ro0x** [comment]
Logging into the server provided the following print out, and a working dialog -

`[ script:esx_identity] Getting player Identifer
[ script:esx_identity] Fetching Information
[ script:esx_identity] This player is not registed!
[  script:es_extended] [INFO]  Player 1 Has been granted admin permissions via Ace Perms.
[ script:esx_identity] This player is not registered, informing client side to send the register!
[  script:es_extended] [INFO] Player "x0Z3ro0x" has connected to the server. ID: 1`

Aside from prints and the removal of a variable that wasn't used, the coding appears to be the same. Yet the dialog properly displayed this time and so far every time after.

Here is the esx_identity I was using from the download on the 13th. What gives?

[esx_identity.zip](https://github.com/esx-framework/esx-legacy/files/7919541/esx_identity.zip)

**Comment by Luke20201** [comment]
Are you saying that the file I sent _works?_

I find this quite odd - as I simply added print's. Please confirm this.

**Comment by x0Z3ro0x** [comment]
Im aware, I compared the code when it did work to see what you did. That's how I know all you did was add prints and remove an un-used variable for if the loading screen has finished.

So why now and why randomly?

**Comment by Luke20201** [comment]
To be honest I don't know. 

I installed a fresh Legacy server with the same thing as you and immediately ran into your issue as well. My fix for that was adding a Citizen.Wait() before enabling the GUI.
As for why yours work's I really can't tell you. I think there's a race condition somewhere, potentially the prints may have given it the millisecond it needed to win the race?


Are you using a Localhost by any chance?

**Comment by x0Z3ro0x** [comment]
Yes I am on a local host. I am going to put in the old one with your changes before the GUI. I have a feeling you're right and it will continue to work. I only think that however because it explains the randomness of working that small few times while failing to loading the full GUI the rest.

Is there anything I can do besides report the results?

**Comment by Luke20201** [comment]
To be honest, I believe this might be a race condition regarding Localhost. The fact that only the two of us have experienced this issue in the near year since the last Identity update mean's it must be uncommon, so I will put it down to a localhost issue. Now, using esx_mutlicharacter prevents this from happening fully. Which in a sense most people do use this so it could be another reason why it's not been reported. 

Let me know if your test works.

**Comment by moffia1200** [comment]
good evening i have problem opening the menu phone annimatsie vmenu and more
@es_extended/client/functions.lua251 attempt to  index a nil lalue (flied '?')

**Comment by Luke20201** [comment]
> good evening i have problem opening the menu phone annimatsie vmenu and more @es_extended/client/functions.lua251 attempt to index a nil lalue (flied '?')

Hi, please create your own issue rather than posting on someone else's on a topic completely unrelated.

**Comment by x0Z3ro0x** [comment]
Apologies for the late reply, I was called into work at the last minute. I did throw in the old script with the citizen wait just before enabling the GUI.

It worked as anticipated. Perhaps I should try multicharacters? Before it would just stay stuck on a view from vinewood hills, never loading in, never giving an error. Could that be somehow related to the race condition of esx identity?

**Comment by Luke20201** [comment]
I don’t think that would be it. I would guess multi character wasn’t installed properly, but honestly it 100% depends on your pc since you’re running FiveM while also acting as the server.

Just to be clear, the Wait *works* or *doesnt work*?

**Comment by x0Z3ro0x** [comment]
The wait works yes. I'll take a look into multicharacter as I tend to follow instructions to the letter, glad it's unrelated though. It's important I tell you that I use localhost, however my personal computer is NOT the server. I have a dedicated server on the same network and so I use localhost.

The connection is behind a dedicated business line just for hosting.

**Comment by Luke20201** [comment]
Thank you for filing the issue! I have committed an optional fix to the resource, to allow anyone else experiencing this issue to fix it themselves. 
Should you find another issue, please create a new issue so we can assist further!
