### ISSUE TITLE
[Bug] - esx_banking - pin code + atm bug

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#592]
**Describe the bug**
1️⃣ cannot set pin code to 0000
2️⃣ setting pin code to 0000 returns notification `That's an invalid amount of money`.
3️⃣ opening atm once, will keep opening atm's even in bank
4️⃣ bad font choice, doesn't support UTF-8

**Comment by ThatPool** [comment]
esx_banking/server/main.lua

In line 51:
Change
`if amount == nil or amount <= 0 then`
To
`if amount == nil or (not typeData.pincode and amount <= 0) then`

In line 82:
Change
`TriggerClientEvent("esx:showNotification", source, TranslateCap(string.format('%s_money', key), amount), "success")`
To
`TriggerClientEvent("esx:showNotification", source, TranslateCap(string.format('%s_money', key), typeData.pincode and (string.format("%04d", amount)) or amount), "success")`

**Comment by iSentrie** [comment]
#598 fix here

**Comment by roadtosixx** [comment]
The font will be changed, I have shared it with the team.

The bugs should be fixed with my PR.

**Comment by Benzo00** [comment]
merged!

**Comment by iSentrie** [comment]
> 

number 3 still persists.

**Comment by iSentrie** [comment]
> merged!

number 3 still persists.

**Comment by iSentrie** [comment]
1. open atm
2. go to bank and open bank
3. atm will open instead of bank
4. ?!

**Comment by roadtosixx** [comment]
Works Fine for me

**Comment by iSentrie** [comment]
https://user-images.githubusercontent.com/29688478/198842833-418548ae-d806-4f61-9de6-bafc8a39902e.mp4

No way

**Comment by iSentrie** [comment]
Even more weird
https://streamable.com/q46275

**Comment by iSentrie** [comment]
After that menu can be opened anywhere, simply press E and atm will open, you can go fishing and still open it.

**Comment by roadtosixx** [comment]
Thats because you use noclip and move away to fast from the Atm

**Comment by roadtosixx** [comment]
I fixed it so its impossible for normal users, but with noclip its buggy
