### ISSUE TITLE
ESX-Skin Menu Closing after Creating a Char

### ISSUE THREAD

**Issue by MarkK-LT** [esx-framework/esx-legacy#61]
Hello,
So I have a Problem with the Skin Menu closing after making a Char, I dont know what happends and no error happen in the Console over txAdmin or F8. Also when trying to move it does not let you. 
We are also using the Multi Char system from ESX-Leagcy

![hm](https://user-images.githubusercontent.com/64864710/151705859-a2695db9-8426-4d5f-aa85-7c6a957f4ca5.PNG)

**Comment by Streammett** [comment]
are using "doors" lock script? 

If yes, thats the problem. You need to modify it and remove "ESX.UI.Menu.CloseAll()".

**Comment by Luke20201** [comment]
Hi,

Did @Streammett fix solve your problem?

**Comment by amgmacht** [comment]
You have to change in your doorsscript and esx_multicharacter :

`ESX.UI.Menu.CloseAll()`

to

`ESX.UI.Menu.Close()`

after works fine for me.
