### ISSUE TITLE
[Bug] - esx_taxijob- Issue

### ISSUE THREAD

**Issue by bitpredator** [esx-framework/esx-legacy#664]
OS: ( Windows/Linux) : Windows
FiveM Artifact: 5993
ESX Version: 1.8.5

Additional context
When trying to generate a vehicle in esx_taxijob, the name is not displayed but is shown as "undefined", this error manifests itself after commit: https://github.com/esx-framework/esx-legacy/pull/653/files

**Comment by Gellipapa** [comment]
#710 Fixed this issue in pull request.  
It will soon be merged.  
You can add new translations if you like. 
Thanks for your patience. 
@bitpredator

**Comment by bitpredator** [comment]
I will upload the Italian translation soon

**Comment by bitpredator** [comment]
Updated translation for the Italian language available in the pull request
[https://github.com/esx-framework/esx-legacy/pull/711](711)
