### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by Gameadictive** [esx-framework/esx-legacy#665]
I just updated to 1.8.5 and for no reason distresssignal from esx_ambulancejob are not working.
When people dies and press G it shows the message for the dead people but nothing in EMS side.

![asd](https://user-images.githubusercontent.com/65845786/200434554-0f178fc9-40c0-4cb4-80ac-9b335cd92e02.PNG)
![dasf](https://user-images.githubusercontent.com/65845786/200434593-4f8efb8e-db04-4066-bc53-0235e88318ae.PNG)
![fads](https://user-images.githubusercontent.com/65845786/200434615-3499b1b4-f2e7-49c6-94ca-faa3b190ea97.PNG)

**Comment by Gameadictive** [comment]
im using npwd phone but i dont want the use of a esx_phone or gcphone for this.

**Comment by Benzo00** [comment]
if u want to add another phone trigger then thats up to you?

**Comment by Benzo00** [comment]
or wdym?

**Comment by Gameadictive** [comment]
esx_ambulancejob only has two options with gcphone or esx_phone why not a option where don´t use a notification on a phone for this?

**Comment by Gellipapa** [comment]
If you use an NPWD phone, you have to add this function because it is not in NPWD either. But if I understand correctly, you don't need it in a phone, you just need a simple notify that signals the online ambulance and it doesn't work/appear?

**Comment by Gameadictive** [comment]
I fixed by do a chat command is more easy.

**Comment by Gellipapa** [comment]
Okay. We'll keep an eye on this in the future, thanks for the tip.
