### ISSUE TITLE
esx_identity delete character

### ISSUE THREAD

**Issue by steliosgaminggr** [esx-framework/esx-legacy#667]
/chardel command gives me that error
![image](https://user-images.githubusercontent.com/65224090/200833773-638de807-70c8-4274-bc74-03ab64fca418.png)

**Comment by tony-stark-17** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/688

**Comment by CsokiHUN** [comment]
Close please @Benzo00

**Comment by Gellipapa** [comment]
Tested works.
