### ISSUE TITLE
oxmysql problem

### ISSUE THREAD

**Issue by ProxyPing** [esx-framework/esx-legacy#687]
hi me again xd, i updated oxmysql to v2.5.4
and since then i cant open the police vehicle shop and i get the message ('you\'re not authorized to buy this kind of vehicles.')

Also i downgraded again to v2.5.3, and it works.

**Comment by Gellipapa** [comment]
Hi! I suggest you don't update to a new version for now, there is nothing very new in this update. Better error handling is built in by Linden.

**Comment by Gellipapa** [comment]
It could be because of async, because I looked at the code and where you get the error message, it asks for each vehicle from Config.lua, based on player job and grade.

**Comment by Gellipapa** [comment]
Hi! Does it work now? @ProxyPing

**Comment by Zzeyy** [comment]
Well, probably not since Proxy said they downgraded again, implying that it did not resolve the problem.

**Comment by Gellipapa** [comment]
> 

I understand but I'm thinking if after downgraded  works again?
