### ISSUE TITLE
esx_society

### ISSUE THREAD

**Issue by Jamal209** [esx-framework/esx-legacy#69]
I got the error when trying to deposit/withdraw society money while use the oxmysql
![s](https://user-images.githubusercontent.com/99092590/152653682-cf3f5948-9c0c-4ac2-9f60-2c46b4a08bd3.png)
.

**Comment by Mycroft-Studios** [comment]
Can u please provide more details :)

**Comment by Jamal209** [comment]
> this error just come from esx_vehicleshop i mean like when ur try to deposit/withdraw on society_cardealer it brings that error..for the other society its fine

**Comment by TheSpaceGamerV2** [comment]
> > this error just come from esx_vehicleshop i mean like when ur try to deposit/withdraw on society_cardealer it brings that error..for the other society its fine

Surely because society_cardealer doesn't exist in the sql

Did u run the sql file ? and do u have download / start the dependencies (https://github.com/esx-framework/esx-legacy/tree/main/%5Besx_addons%5D/esx_vehicleshop)

**Comment by Jamal209** [comment]
> > > this error just come from esx_vehicleshop i mean like when ur try to deposit/withdraw on society_cardealer it brings that error..for the other society its fine
> 
> Surely because society_cardealer doesn't exist in the sql
> 
> Did u run the sql file ? and do u have download / start the dependencies (https://github.com/esx-framework/esx-legacy/tree/main/%5Besx_addons%5D/esx_vehicleshop)

![Untitled](https://user-images.githubusercontent.com/99092590/152696852-22187e5c-04e5-4fb2-bd98-0bc6e1d49ecc.png)
i did installed the latest file from legacy and also the database include i check all the depencies too and include the oxmysql. and i did remove async since legacy use oxmysql
