### ISSUE TITLE
[Bug] - esx_garages - Issue

### ISSUE THREAD

**Issue by tommycentral** [esx-framework/esx-legacy#703]
**Describe the bug**
I purchase a car from the dealership, which i then go to store in the esx_garage. But, when i restart the server or /dv my owned car, it will appear in the impound. i then click 'impound' which impounds the car and waypoints me to the impound, i then go and spend 3k to get it out, the car then spawns with a totally random plate which isnt mine, then i go and try to store the vehicle and it says i dont own it? I then check the garage again and its back under the impound list?

**To Reproduce**
{IN-GAME}
1. Go to dealership and buy a vehicle using the esx_vehicleshop
2. Go and store the car in a garage.
3. Restart server, then go to the garage to retrieve the car... and it will be in impound. Press impound to impound it.
4. Go and collect the car from the impound, and press 'pay 3k' and it will spawn the car for you.
5. The plate on the car wont match your plate, and then trying to re-store the car will fail and say its not yours.
6. Then head back to a garage and the car will be back in the impound?

**Expected behavior**
When paying the impound amount, car should spawn 'as yours' but isnt doing.

**Screenshots**
Car back in impound - https://gyazo.com/33a2528c413961e056a441804b416d5c
I apparently dont own it when paying fee - https://gyazo.com/d752de861a109bcdda4bd84e3092dd72

**Debug Info (please complete the following information):**
 - OS: txAdmin [Linux]
 - FiveM Artifact: https://gyazo.com/5adc878869a8e0f4aa4a24146b5b4f62 (Game version: 1604)
 - ESX Version: 1.8.5

**Additional context**
Tested on multiple custom cars in the dealership which ive added, still the same outcome.

**Comment by tommycentral** [comment]
After further testing, it seems like when the server has restarted and you head for your vehicle from impound, this is when it glitched and bugs out and gives you a car that isnt yours... after trying to store that vehicle and then go back to impound, you press pay 3k and it gives you the correct car with your plate, basically your car..

here is a video run down for anyone who might be a little confused: https://www.youtube.com/watch?v=Crmy53TCeKU

**Comment by notjuswaaa** [comment]
Have the same issue here

**Comment by wobozkyng** [comment]
I had the issue too, but not always. It is like the vehicle properties had not been set to the spawned vehicle.
In my case, if I go away from the spawned vehicle in impound and back (from impound teleport to closest garage then teleport back to impound), the properties would be set.

**Comment by tommycentral** [comment]
> I had the issue too, but not always. It is like the vehicle properties had not been set to the spawned vehicle. In my case, if I go away from the spawned vehicle in impound and back (from impound teleport to closest garage then teleport back to impound), the properties would be set.

Exactly same as my issue, but still needs a fix lol. Like I mentioned, only happens with custom vehicles.. very weird bug.

**Comment by wobozkyng** [comment]
Hi, been a while. I made a PR #733

**Comment by Rav3n95** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/733
