### ISSUE TITLE
[Bug] - esx_context and Multicharacter

### ISSUE THREAD

**Issue by Mattt2283** [esx-framework/esx-legacy#704]
**Describe the bug**
When loading in the multicharacter will open when you select the character you want to play as and hit backspace or esc it will remove the context menu that has play, return, delete. then you will be stuck

**To Reproduce**
1. load into multicharacter
2. Select Character
3.  Hit backspace or esc.

**Expected behavior**
for the menu to just stay up not dissapear.

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact:  6043
 - ESX Version: Latest Version, Fresh Install. 1.8.5

**Comment by Rav3n95** [comment]
That will be a esx_context "bug"

**Comment by Gellipapa** [comment]
Hi! To fix the bug we need to make changes to esx_context we will fix the bug soon. @Mattt2283

**Comment by Mattt2283** [comment]
Alright thanks guys appreciate all of you.
