### ISSUE TITLE
[Bug] - esx_multicharacter - Skin menu not opening on registering a new character

### ISSUE THREAD

**Issue by staendidev** [esx-framework/esx-legacy#712]
**Describe the bug**
So i wanted to create a new char, hit register...
Then i froze and got this error message
All of our players get this issue
https://prnt.sc/V_hdLlNhZ9z2

**To Reproduce**
1. Go to the server
2. Click on new character
3. Click register

**Screenshots**
https://prnt.sc/V_hdLlNhZ9z2

**Debug Info (please complete the following information):**
 - OS: Linux
 -  FiveM Artifact 6043
 - ESX Version: newest

**Comment by Gellipapa** [comment]
Hi! @staendidev Compare the two codes. It's probably already fixed try to update ESX and retest. I wait for feedback thanks.
![image](https://user-images.githubusercontent.com/22717950/204145234-df39e31d-3e07-4948-b3b3-134a85e34d49.png)

**Comment by Rav3n95** [comment]
Since there is not a singe feedback, i close the issue as solved!
