### ISSUE TITLE
[Bug] - esx_menu_default - Menu items not being shown

### ISSUE THREAD

**Issue by Corencas** [esx-framework/esx-legacy#717]
Am a complete newbie to fiveM and ESX and all this. I just created a server and I logged in and I wanted to go talk to a drug dealer at a shop on the beachwalk but I walk in the circle, press E, and the menu shows up just no items under it..

Also my phone is stuck in French and I really need to change that too lol

I read from other places that I might not have my start list for my mods in the correct order in the server config, but I haven't changed it besides inputting my other mods at the bottom. They also have the version number in the folder name, is that a problem?

I would love some help..thank you!

https://gyazo.com/331d30cf0a96223b35ec8ddcef163bee

**Comment by Gellipapa** [comment]
Hi! @Corencas Which es_extended version use?  Do you use latest esx version?

**Comment by Corencas** [comment]
Yes I believe so...it's not the legacy version I can say that for sure.

**Comment by Corencas** [comment]
> Hi! @Corencas Which es_extended version use? Do you use latest esx version?

Yes I believe so...it's not the legacy version I can say that for sure.

**Comment by Gellipapa** [comment]
@Corencas You should use latest legacy version, you can download this repository.

**Comment by Corencas** [comment]
> @Corencas You should use latest legacy version, you can download this repository.

I actually have the ESX v1-Final Pack V1.6 that I got from my server host..is that different than the legacy version? Sorry I'm just not familiar with any of this, and don't want to change to a new mod and get errors or something

**Comment by Gellipapa** [comment]
@Corencas It is important that you use the latest version of this repo, because there have been changes in the past and they have been fixed. ESX is undergoing a major change so we are fixing all the bugs and rewriting the scripts for a better experience.

**Comment by Benzo00** [comment]
> > @Corencas You should use latest legacy version, you can download this repository.
> 
> I actually have the ESX v1-Final Pack V1.6 that I got from my server host..is that different than the legacy version? Sorry I'm just not familiar with any of this, and don't want to change to a new mod and get errors or something

you should update yes you most likely will have more bugs with your current version than u would have with the latest!
