### ISSUE TITLE
[Bug] - esx_addonaccount - Issue

### ISSUE THREAD

**Issue by Zzeyy** [esx-framework/esx-legacy#723]
**Describe the bug**
No idea, really. I had some unused jobs and addon accounts which weren't supposed to exist,
but removing those didn't help with the error at all. I replaced the addonaccount script with the one from this
github repository multiple times just to make sure, didn't help either.
I also checked if any other esx script isn't outdated and that's not it either.

I also think this affects how the money in the job accounts "update".
Let's say I take $20K from $290K and then do some mechanic work on a vehicle, instead of
subtracting the spent money from the $270K it reverts back to $290K and subtracts from that instead.

**To Reproduce**
1. Launch server
2. See error

```
[script:esx_addonacco] SCRIPT ERROR: @esx_addonaccount/server/main.lua:18: table index is nil
[script:esx_addonacco] > handler (@esx_addonaccount/server/main.lua:18)
[script:esx_addonacco] > <unknown> (@oxmysql/dist/build.js:22252)
[script:esx_addonacco] > processTicksAndRejections (node:internal/process/task_queues:96)
```

**Expected behavior**
There should be no error. And there should be no money dupe with the job accounts.

**Debug Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - FiveM 6079
 - ESX Version: 1.8.5

**Comment by Zzeyy** [comment]
I did import the sql a long time ago. But not too long for anything to change.

**Comment by Gellipapa** [comment]
@Zzeyy  Hi! 

```
SELECT * FROM addon_account 
LEFT JOIN addon_account_data ON addon_account.name = addon_account_data.account_name 
UNION 
SELECT * FROM addon_account 
RIGHT JOIN addon_account_data ON addon_account.name = addon_account_data.account_name
```
 Here you can see that there are two table connections. 
 I think you should update your database tables. 
 Check addon_account_data,addon_account table and recreate.
 
 Let's hope it solves the problem. Report back and I look forward to your reply.

**Comment by Zzeyy** [comment]
This is the result
`/* Affected rows: 0  Found rows: 448  Warnings: 0  Duration for 1 query: 0.016 sec. (+ 0.016 sec. network) */`

**Comment by Zzeyy** [comment]
```
[  script:esx_society] SCRIPT ERROR: @esx_society/server/main.lua:24: attempt to index a nil value (field '?')
[  script:esx_society] > handler (@esx_society/server/main.lua:24)
[  script:esx_society] > <unknown> (@oxmysql/dist/build.js:22252)
[  script:esx_society] > processTicksAndRejections (node:internal/process/task_queues:96)
```
Now this error appears

**Comment by Gellipapa** [comment]
@Zzeyy You should upgrade the whole ESX, because I can't tell you what else is related to money. Now you were just lucky that I had the query and could tell you the problem :)

**Comment by Gellipapa** [comment]
I think full database table reset, and full resource copy and paste.

**Comment by Zzeyy** [comment]
I did upgrade the whole ESX. Replaced all of the files for the addons too.

**Comment by Gellipapa** [comment]
It is not clear to me whether this money is now fraction money or what is not updated?

**Comment by Zzeyy** [comment]
I think I need to explain myself better, but it's really hard, so I'll tell you what to do to experience the bug.

• Open boss menu
• Take some money (let's say we take $5K from $50K that's already there, we end up with $45K in the fraction)
• Go tune a car `esx_lscustom`, (pay $3K for the modifications)
• Then open the boss menu and check the money balance
• There's $47K ($3K got subtracted from $50K)

**Comment by Zzeyy** [comment]
When putting money in the fraction society the money is updated in the database.
But the script acts as if the money wasn't added.

**Comment by Gellipapa** [comment]
Try revert this commit: https://github.com/esx-framework/esx-legacy/commit/d5661c1a9acd4aecea57870f2dabe7a87ac6701a and try test please. The important thing is that the version committed by linden should be the last one for you, because there were changes after that and most likely that's why it's bad for you.

**Comment by Zzeyy** [comment]
I can't really tell what reverting means. 😂
What you sent is the older version of the code, yes?
Fyi I updated from 1.5.3 to 1.8.5.

**Comment by Gellipapa** [comment]
No problem i will check later.

**Comment by Unavarage** [comment]
![1](https://user-images.githubusercontent.com/31205336/205715560-dde3f8a5-37d6-4f70-a9c4-1f19ce7631e8.png)
Hi I have the same issue, but my esx actually is clean I tried a clean install on my own pc and without any resource have the same isue.. :/

**Comment by Unavarage** [comment]
> > ![1](https://user-images.githubusercontent.com/31205336/205715560-dde3f8a5-37d6-4f70-a9c4-1f19ce7631e8.png) Hi I have the same issue, but my esx actually is clean I tried a clean install on my own pc and without any resource have the same isue.. :/
> 
> Update your ESX

I already have the latest :(

**Comment by Gellipapa** [comment]
Hi! @Unavarage Download the latest ESX and also update the database table. This must be a database data error.

**Comment by Unavarage** [comment]
> Hi! @Unavarage Download the latest ESX and also update the database table. This must be a database data error.

Ok, thanks I will look into it.

**Comment by Unavarage** [comment]
So I actually found a better solution, because my public server obviously is modded and the sql already modified in different parts, If anyone has this problem delete addon_account and addon_account_data tables from the sql then simply re drop it in the two tables, the error should be fixed. Thanks for the help by everyone.

**Comment by Gellipapa** [comment]
Problem solved thank you retest @Unavarage.
