### ISSUE TITLE
[Bug] - esx_textui - esx_garage, esx_vehicleshop

### ISSUE THREAD

**Issue by Rayzer567** [esx-framework/esx-legacy#726]
**Describe the bug**
When you try to go near the markers of those scripts listed from the title (esx_garage, esx_vehicleshop) it doesnt show any text ui but a error in the console

**To Reproduce**
1. Go to 'esx_vehicleshop marker location'
2. go near the marker
3. Text ui doesn't show

1. Go to 'esx_garage marker location'
2. go near the marker
3. Text ui doesn't show

**Expected behavior**
Its expected to show the esx_textui but it doesn't

**Screenshots**
![image](https://user-images.githubusercontent.com/80643454/205464936-822a4446-1a29-4a8f-8a44-10d94185000f.png)
![image](https://user-images.githubusercontent.com/80643454/205464992-30c7cab9-5492-4a88-ad34-a76dc7dcf95f.png)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact: 6110
 - ESX Version: the newest possible fresh server (1.8.5 - main branch)

**Additional context**
These esx_textui bugs have been in esx 1.8.5 for a long time

**Comment by CsokiHUN** [comment]
Previously fixed by @Rav3n95 but overwritten with the wrong one. 🤣
wrong: [commit](https://github.com/esx-framework/esx-legacy/commit/8cb620dfe1721c865ff2609503334e0f624ce8a7) 
good: [commit](https://github.com/esx-framework/esx-legacy/commit/b2be63f5f4a0697216365ea56adb3ce822eac79e)

**Comment by Rav3n95** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/742
