### ISSUE TITLE
[Bug] - esx_banking - GetNetworkObject: no object

### ISSUE THREAD

**Issue by bitpredator** [esx-framework/esx-legacy#736]
**Describe the bug**
When loading into game pressing F8 key (console) shows **Warning: [entity] GetNetworkObject **

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux): Windows
 -  FiveM Artifact: 6129
 - ESX Version: 1.8.5

![esx_banking bug](https://user-images.githubusercontent.com/67551273/206852807-7926dc64-123f-49e5-a5be-50f672f5213c.PNG)

**Comment by Rav3n95** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/744
