### ISSUE TITLE
Dead by fall or carcrash

### ISSUE THREAD

**Issue by Bulle93230** [esx-framework/esx-legacy#738]
If you die by a fall or a car crash, your ped is dead but you can't have the death screen

**Comment by iSentrie** [comment]
do you use latest version? it was fixed i think

**Comment by Rav3n95** [comment]
@Bulle93230 have you tried this? https://github.com/esx-framework/esx-legacy/commit/ebc47b714be392c71c2e34b9d9e850b9765fb95d

**Comment by tony-stark-17** [comment]
Tried reproducing it but couldn't in the latest version
