### ISSUE TITLE
[Bug] - Set vehicle extras always sets extras to 0

### ISSUE THREAD

**Issue by Clink1234** [esx-framework/esx-legacy#739]
**Describe the bug**
See `client/functions.lua` of es_extended...

SetVehicleProperties the extras are set like this: SetVehicleExtra(vehicle, tonumber(extraId), enabled and 0 or 0)

Won't enabled and 0 or 0 always evaluate to 0?

Changed in this commit: https://github.com/esx-framework/esx-legacy/commit/f944cd2455b78dc041a8e872ed220d5c3c75d41d

Was Previously...
```
if props.extras ~= nil then
    for extraId, enabled in pairs(props.extras) do
        if enabled then
            SetVehicleExtra(vehicle, tonumber(extraId), 0)
        else
            SetVehicleExtra(vehicle, tonumber(extraId), 1)
        end
    end
end
```

This breaks SetVehicleExtras...

**Comment by Rav3n95** [comment]
@Clink1234 can you send a pr to fix that issue if you already know the soultion? Thanks a lot

**Comment by Rav3n95** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/743
