### ISSUE TITLE
[Bug] - esx_identity - Issue

### ISSUE THREAD

**Issue by hasidu** [esx-framework/esx-legacy#746]
**Describe the bug**
after i installed tx admin esx template i got esx_identity error that after i fill my identity it doesn't do anything just give me again same page to fill identity

**Screenshots**
![image](https://user-images.githubusercontent.com/72035642/207951996-15d63ed8-0a2e-4012-8672-c851e16a030a.png)

**Debug Info (please complete the following information):**
 - OS: ( Windows)
 -  FiveM Artifact latest one exit 13/12/2022
 - ESX Version: tx admin latest one

**Comment by Rav3n95** [comment]
Try the lastest from github please

**Comment by hasidu** [comment]
this one ?

![image](https://user-images.githubusercontent.com/72035642/207964756-7bce7674-a862-4827-b1db-fad2209ec4ac.png)

**Comment by Rav3n95** [comment]
yes

**Comment by hasidu** [comment]
done thank you

**Comment by Rav3n95** [comment]
fixed it?

**Comment by tony-stark-17** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/748

**Comment by hasidu** [comment]
> fixed it?

yes thank you
