### ISSUE TITLE
[Bug] - esx_banking - Issue No Object by ID

### ISSUE THREAD

**Issue by Cluts** [esx-framework/esx-legacy#757]
This happens as soon as someone Logs into the server

![image](https://user-images.githubusercontent.com/6239217/208321051-71b262f0-22c5-41c3-8097-3541eaba7666.png)

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux) = Windows
 -  FiveM Artifact = Latest by now
 - ESX Version: = Latest by now

This "No Object by ID ****** " also used to happen when I spawned a /car and I solved this by reducing ped & traffic density.

**Comment by bitpredator** [comment]
@Cluts Fixed in https://github.com/esx-framework/esx-legacy/pull/744

**Comment by Cluts** [comment]
@bitpredator Thank you so much! Fixed Already <3
