### ISSUE TITLE
ESX Identity not showing up

### ISSUE THREAD

**Issue by Xxpromw3mtxX** [esx-framework/esx-legacy#76]
Hello guys, I'm trying to upgrade from the older version and with the new one when joining the server the identity doesn't show up.
If I stop the plugin I can walk and do everything.

https://streamable.com/301bj3

**Comment by Cola96** [comment]
Did ya set everything in the database?

Can u send the users table?

**Comment by PsychoShock** [comment]
Do you have `esx_multicharacter` on the server? Seem's to act weird when set to false.

**Comment by Xxpromw3mtxX** [comment]
No I don't have the multichar and is it's set to false.
The user table is correct

**Comment by baguscodestudio** [comment]
> Hello guys, I'm trying to upgrade from the older version and with the new one when joining the server the identity doesn't show up. If I stop the plugin I can walk and do everything.
> 
> https://streamable.com/301bj3

Try the esx_identity from this #79 it should be fixed in there.

**Comment by Mycroft-Studios** [comment]
> > Hello guys, I'm trying to upgrade from the older version and with the new one when joining the server the identity doesn't show up. If I stop the plugin I can walk and do everything.
> > https://streamable.com/301bj3
> 
> Try the esx_identity from this #79 it should be fixed in there.

Merged PR , should be fixed now :)
