### ISSUE TITLE
Docs down?

### ISSUE THREAD

**Issue by jaoryx** [esx-framework/esx-legacy#765]
It's been for some time now, I keep checking over some time but it seems to be down I guess

**Comment by Gellipapa** [comment]
Hi! You can find here: https://connect.esx-framework.org/

**Comment by C4-KTTK** [comment]
> Hi! You can find here: https://connect.esx-framework.org/

Thanks!

**Comment by jaoryx** [comment]
> Hi! You can find here: https://connect.esx-framework.org/

Thanks indeed!! I've been searching all over the place 😅 their new website still redirects to the old docs website
