### ISSUE TITLE
[Bug] - esx_license - Issue

### ISSUE THREAD

**Issue by Cluts** [esx-framework/esx-legacy#769]
**Describe the bug**
When I try to buy boat license (money gets discounted) this happens on console and I don't get the "Boat License":
![image](https://user-images.githubusercontent.com/6239217/209301697-abdbf7be-d57d-4e71-920c-c2629476bdf5.png)

**To Reproduce**
1. Go to 'Boat Shop'
2. Click on 'Buy boat license for $50000'
3. Scroll down to '-'

**Expected behavior**
Recieve license after I pay $50000 for it.

**Screenshots**
![image](https://user-images.githubusercontent.com/6239217/209301837-6a9f00ba-b787-42b0-989c-f6da76276c80.png)

**Debug Info (please complete the following information):**
 - OS: Windows
 -  FiveM Artifact : 5848
 - ESX Version: 1.8.5 Legacy

**Additional context**

**Comment by bitpredator** [comment]
Hi, make sure the boat license is in the database.

**Comment by bitpredator** [comment]
I fixed this in the request: https://github.com/esx-framework/esx-legacy/pull/770

**Comment by Cluts** [comment]
I think problem is here but I can't identify it.
esx_license/server/main.lua
![image](https://user-images.githubusercontent.com/6239217/209333830-fa4c8d43-7ae3-40c3-9d44-c1d6ee151dc6.png)
and my License SQL is like this:
![image](https://user-images.githubusercontent.com/6239217/209333906-cdac4f4d-9ed3-4b33-909d-f6ac058a1db4.png)

**Comment by bitpredator** [comment]
> I think problem is here but I can't identify it. esx_license/server/main.lua ![image](https://user-images.githubusercontent.com/6239217/209333830-fa4c8d43-7ae3-40c3-9d44-c1d6ee151dc6.png) and my License SQL is like this: ![image](https://user-images.githubusercontent.com/6239217/209333906-cdac4f4d-9ed3-4b33-909d-f6ac058a1db4.png)

license type is not "boating" but "boat"

**Comment by Cluts** [comment]
Yes, I've seen that in ur posted .sql, I renamed it but FiveM seems to be offline so couldn't test it yet! Thanks for ur time & help!
