### ISSUE TITLE
error with mask

### ISSUE THREAD

**Issue by nuageee** [esx-framework/esx-legacy#77]
Hello,
I have a problem with esx_datastore and es_extended

Esx_datastore tell me:
` SCRIPT ERROR: @esx_datastore/server/main.lua:36: attempt to get length of a nil value (field '?')`

and es_extended tell me : 
`SCRIPT ERROR: error object is not a string`

this message appear when i trying to remove a mask

**Comment by Cola96** [comment]
same problem with clothesaving in the another issue

**Comment by PsychoShock** [comment]
This https://github.com/PsychoShock/esx-legacy/blob/0523a8d22c7d5392f7f89c7659bf973f78c7e090/%5Besx_addons%5D/esx_datastore/server/main.lua#L36 ? 

If yes, can you explain me how to you have this error?

Thanks

**Comment by nuageee** [comment]
hey so this error appear when i try to remove a mask with menu 'k' or another menu

**Comment by BENJYYI** [comment]
Hey, do you have the solution please ? I have th error too !

**Comment by Ultra-Meloncrafter** [comment]
i know this post is about 1 or more years old, but did ever fix this error?
