### ISSUE TITLE
Problem with esx_datastore 

### ISSUE THREAD

**Issue by Cola96** [esx-framework/esx-legacy#78]
I can't get the Clothing to save in the Database Permanetly. If i delete the clothing from the datastore_data and restart esx_clotheshop it temporarily saves an i can acces it for the session but if i restart it isn't there anymore. If i try to save it again it give this error.  I did everything as discribed.

[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/classes/datastore.lua:25: attempt to index a string value (upvalue 'data')
[script:esx_datastore] > ref (@esx_datastore/server/classes/datastore.lua:25)
[script:esx_datastore] > ref (@esx_accessories/server/main.lua:15)
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:58)
[script:esx_datastore] > handler (@esx_accessories/server/main.lua:14)
[script:esx_datastore] SCRIPT ERROR: error object is not a string

-----------------------------------------------------------------------------------
 @esx_datastore/server/classes/datastore.lua:24-27:

24 self.set = function(key, val)
25		data[key] = val
26		self.save()
27	end
------------------------------------------------------------------------------------
@esx_accessories/server/main.lua:14-24)

14	TriggerEvent('esx_datastore:getDataStore', 'user_' .. string.lower(accessory), xPlayer.identifier, function(store)
15		store.set('has' .. accessory, true)
16
17		local itemSkin = {}
18		local item1 = string.lower(accessory) .. '_1'
19		local item2 = string.lower(accessory) .. '_2'
20		itemSkin[item1] = skin[item1]
21		itemSkin[item2] = skin[item2]
22
23		store.set('skin', itemSkin)
24	end)
--------------------------------------------------------------------------------------
@esx_datastore/server/main.lua:58

58     AddEventHandler('esx_datastore:getDataStore', function(name, owner, cb)
59    	cb(GetDataStore(name, owner))
60     end)
--------------------------------------------------------------------------------------

You'll probably hate me because I pasted the code in that way

If you need anymore infos i can give it to ya hopefully.

**Comment by thelindat** [comment]
Should be fixed (json string wasn't being decoded)

**Comment by Cola96** [comment]
ok thank you man
