### ISSUE TITLE
It is opened from number 4 I just want to delete this

### ISSUE THREAD

**Issue by MahmoudyTech** [esx-framework/esx-legacy#781]
It is opened from number 4 I just want to delete this
![image-2](https://user-images.githubusercontent.com/39407574/209851147-c1c72670-d6a7-4588-9175-f72e7668e854.png)

**Comment by Gellipapa** [comment]
Hi! @MahmoudyTech  This is default inventory, you can disabled in es_extended config.lua. Find these text: "Config.EnableDefaultInventory   = true " and change true to false and restart your server.

**Comment by MahmoudyTech** [comment]
![image-4](https://user-images.githubusercontent.com/39407574/209959680-b2b55287-94d4-4db4-9071-54264d6e8c63.png)
:( Unfortunately, it didn't work

**Comment by MahmoudyTech** [comment]
es_extended 1.9.0 There are many problems with it, there are many scripts that do not work on it, and it works on 1.8.5

**Comment by Gellipapa** [comment]
Hi! @MahmoudyTech I will look into the problem and get back to you.

**Comment by Gellipapa** [comment]
Have you switched from F2?

**Comment by MahmoudyTech** [comment]
default inventory open from number 4
It also opens randomly. My inventory opens from f2

**Comment by Gellipapa** [comment]
Hi! I tested and not opens 4 number but today fix @CsokiHUN similar inventory problem please update your version and retest please. Don't forget change true to false in Config.lua (DefaultInventory).

**Comment by Benzo00** [comment]
Like gelli said, inventory is fixed! download latest

**Comment by MahmoudyTech** [comment]
You will download and try again and I will inform you of the result

**Comment by MahmoudyTech** [comment]
The problem has been successfully resolved, thank you
