### ISSUE TITLE
[Bug] - sessionmanager - esx:getSharedObject

### ISSUE THREAD

**Issue by Unavarage** [esx-framework/esx-legacy#788]
**Describe the bug**
Sessionmanager writes in console used esx:getSharedObject method that should not be used.

**To Reproduce**
1. After the server starts up fully the last massage from console is this

Is there anyway to fix this?

**Screenshots**
![11](https://user-images.githubusercontent.com/31205336/209948076-4106ce00-937e-43af-ae9f-d2ab7bd72ef4.png)

**Debug Info:**
 - OS: Windows
 -  FiveM Artifact 6163
 - ESX Version: 1.9.0

**Comment by CsokiHUN** [comment]
use the new export: [docs](https://documentation.esx-framework.org/tutorials/sharedevent)
```lua
ESX = exports["es_extended"]:getSharedObject()
```

**sessionmanager** is not part of **esx-legacy**

**Comment by Unavarage** [comment]
> use the new export: [docs](https://documentation.esx-framework.org/tutorials/sharedevent)
> 
> ```lua
> ESX = exports["es_extended"]:getSharedObject()
> ```
> 
> **sessionmanager** is not part of **esx-legacy**

I know that it's not part of esx-legacy, but looks like esx that causes problem with sessionmanager.

**Comment by Mycroft-Studios** [comment]
> > use the new export: [docs](https://documentation.esx-framework.org/tutorials/sharedevent)
> > ```lua
> > ESX = exports["es_extended"]:getSharedObject()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **sessionmanager** is not part of **esx-legacy**
> 
> I know that it's not part of esx-legacy, but looks like esx that causes problem with sessionmanager.

hate to say it, but if its in sessionmanager, you have a backdoor/virus on your server
