### ISSUE TITLE
esx_optionalneeds v1.9.0 but deprecated

### ISSUE THREAD

**Issue by iSentrie** [esx-framework/esx-legacy#791]
Optional needs was bumped to 1.9.0, but still uses deprecated methods

https://documentation.esx-framework.org/addons/esx_basicneeds/events/ondrink

https://github.com/esx-framework/esx-legacy/blob/17f96a74ae1a0b812d87694e9ddfe2c3748b2f2d/%5Besx_addons%5D/esx_optionalneeds/server/main.lua#L8

**Comment by Benzo00** [comment]
incorrect, esx_basicneeds uses new events.

**Comment by Benzo00** [comment]
esx_basicneeds, not the same as esx_optionalneeds

**Comment by always91** [comment]
i have same problem how to fix ? 
thanks
