### ISSUE TITLE
[Bug] - esx_ambulancejob 

### ISSUE THREAD

**Issue by always91** [esx-framework/esx-legacy#796]
**Describe the bug**

**To Reproduce**
1. Go to 'all lookroom'
2. Click on 'specific outfit police-ambulance ect..'
3. Scroll down to ''
4. SCRIPT ERROR: @esx_ambulancejob/client/job.lua:429: attempt to index a nil value (local ['jobSkin')](url)

**Expected behavior**
I expected him to change clothes on duty and change into civilian clothes as well

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/66338911/210116135-4938ab68-0edb-4432-8185-5dd634420a7a.JPG)

**Debug Info (please complete the following information):**
 - OS: ( Windows10)
 -  FiveM Artifact 6181
 - ESX Version: esx legacy 1.9.0

if I modify the ambulancejob code on the medical uniform side, it works, but not for civilian clothes

**Comment by Gellipapa** [comment]
Hi! I now tested and works perfectly please download latest version and recheck. I use 1.9.0 es_extended, 1.9.0 ambulance job. Thank you for report and retest.
