### ISSUE TITLE
[Bug] - es_extended - default inventory still showing

### ISSUE THREAD

**Issue by ProxyPing** [esx-framework/esx-legacy#819]
**Describe the bug**
The default inventory is showing but in config it is set to false (also just on drop and on pickup)

**To Reproduce**
1. Get a other inventory
2. Set EnableDefaultInventory to false
3. Drop or pickup a item
4. default inventory is still showing.

**Expected behavior**
It should not show after it is set to false.

**Screenshots**
[https://proxyping.dev/?f=🏈🌱⛷️🤩💄.png](https://proxyping.dev/?f=%F0%9F%8F%88%F0%9F%8C%B1%E2%9B%B7%EF%B8%8F%F0%9F%A4%A9%F0%9F%92%84.png)

**Debug Info (please complete the following information):**
 - OS: Linux
 - Artifact: 6185
 - ESX Version: 1.9.0

**Comment by Gellipapa** [comment]
Hi @ProxyPing I think @CsokiHUN has solved the problem, please test again and let us know.

**Comment by Benzo00** [comment]
Fixed - Download latest and try :)
