### ISSUE TITLE
[Bug] - esx_banking - Issue

### ISSUE THREAD

**Issue by Sarunas2024** [esx-framework/esx-legacy#821]
**Describe the bug**
when u open bank and close it show  press e to open..bat when u teleport to some where from atm or bank   it still show press to open atm or bank ..it wont close  ESX.HideUI()

**Comment by JackDUpModZ** [comment]
@Rav3n95 Please review.

**Comment by Rav3n95** [comment]
I don't want to be that guy, but why would the player teleport away? :D Ill have a look

**Comment by JackDUpModZ** [comment]
> I don't want to be that guy, but why would the player teleport away? :D Ill have a look

That is my thoughts also, However it's a bug none the less, Unless it affects performance needs fixed please 🙏

**Comment by Rav3n95** [comment]
#821

**Comment by JackDUpModZ** [comment]
Resolved with newest PR

**Comment by Sarunas2024** [comment]
it same with atm wgen u teleport from spot not only with bank

**Comment by Sarunas2024** [comment]
i did test with bank all good
now

**Comment by Sarunas2024** [comment]
now is only atm problem

**Comment by Sarunas2024** [comment]
wont close textui when u teleport from atm....

**Comment by Sarunas2024** [comment]
when u fill fix the atm textui
