### ISSUE TITLE
[Bug] - esx_banking

### ISSUE THREAD

**Issue by Sarunas2024** [esx-framework/esx-legacy#831]
u did fix bank  not is all good it close text ui when u teleport from the bank,,,....

bat u dint fix atm   when u teleport from atm it still show text ui and u can open amt

**Comment by Gellipapa** [comment]
@Sarunas2024 Hi! Thank you for report. @Rav3n95 Fixed this issue, coming soon available you.

**Comment by Benzo00** [comment]
Fixed in https://github.com/esx-framework/esx-legacy/pull/838, waiting to test then merge
