### ISSUE TITLE
[Bug] - esx_script - Issue

### ISSUE THREAD

**Issue by MahmoudyTech** [esx-framework/esx-legacy#833]
Everything was done in es_extended 1.8.5
After the update es_extended 1.9.0 this error appears

![image](https://user-images.githubusercontent.com/39407574/212329353-231638e5-e3d1-49e8-839b-bb885c89c0c0.png)

Citizen.CreateThread(function()
    Heap.ESX.RegisterServerCallback("chames_ambulance_medic:requiredAmount", function(source, callback)
        local character = Heap.ESX.GetPlayerFromId(source)

        if not character then return callback(false) end

        local playersInJob = GetPlayersWithJob("ambulance")

        callback(playersInJob <= 0)
    end)
end)

**Comment by CsokiHUN** [comment]
you use getSharedObject export? or old event? 
[https://documentation.esx-framework.org/tutorials/sharedevent/](https://documentation.esx-framework.org/tutorials/sharedevent/)

**Comment by Rav3n95** [comment]
Its not a offical esx resouce, use the support chanel on discord. Thanks, have a great one!
