### ISSUE TITLE
Stuck on Loading Screen.

### ISSUE THREAD

**Issue by Desync3** [esx-framework/esx-legacy#836]
![image](https://user-images.githubusercontent.com/49792134/212472058-36358324-4cde-452a-96d0-ba6eba3a2351.png)
![image](https://user-images.githubusercontent.com/49792134/212472066-1d0660c1-22cd-4e0e-9d3e-82b71d69c72a.png)

![image](https://user-images.githubusercontent.com/49792134/212472131-f39f06e1-bfd1-4e04-99fe-735409652b9a.png)

I can't start anything.

I installed everything correct. I have xammp mysql on. i have the es_extended database. Whats the issue?

**Comment by MoskalykA** [comment]
![image](https://user-images.githubusercontent.com/100430077/212476970-24947d1b-bcdc-49c7-bf2b-9aae9924e403.png)
You need to add the oxmysql resource: https://github.com/overextended/oxmysql

**Comment by Gellipapa** [comment]
@Desync3 Hi! Thank you for report problem. You should update the entire ESX resource pack to get everything working properly.
