### ISSUE TITLE
[Bug] - esx_property - Issue

### ISSUE THREAD

**Issue by yoAmpar** [esx-framework/esx-legacy#841]
**Describe the bug**
script error when starting the script

**Expected behavior**
the script to start

**Screenshots**
[[If applicable, add screenshots to help explain your problem.]

https://imgur.com/njrCRGB

**Debug Info (please complete the following information):**
 - OS: ( Windows/Linux) windows
 -  FiveM Artifact 6208
 - ESX Version: latest

**Comment by Benzo00** [comment]
your not on the latest ESX
