### ISSUE TITLE
attempt to index a nil value (global 'esx')

### ISSUE THREAD

**Issue by smack893** [esx-framework/esx-legacy#842]
previously i was using the 1.1 and 1.2 version but i am pretty impress with the new version but i am having some issue like in prevous version i write few scripts but that scripts not working anymore with new version all scripts show attempt to index a nil value (global 'esx') error so could you please tell me is the global esx remove from this version if not how can i use with 1.9 version

**Comment by CsokiHUN** [comment]
https://documentation.esx-framework.org/tutorials/sharedevent/
