### ISSUE TITLE
ESX Society

### ISSUE THREAD

**Issue by LeguDe** [esx-framework/esx-legacy#97]
Can you add a security check at server main.lua if the player isBoss before withdrawing money, do be more modder save

Line 67
`if xPlayer.job.name == society.name then`

Like in 253ff

```
local isBoss = xPlayer.job.grade_name == 'boss'
	if isBoss then

		local xTarget = ESX.GetPlayerFromIdentifier(identifier)
```

**Comment by Mycroft-Studios** [comment]
That is serverside, modders cannot change this value
